import type { Lesson } from "@/lib/course/lessons";

// Cours N4, partie 2 « Les formes des verbes » : potentiel, obligation,
// transitifs et intransitifs, passif, causatif, verbes composés.
export const N4_VERBES_LESSONS: Omit<Lesson, "number">[] = [
  {
    id: "n4-potentiel",
    title: "Savoir et pouvoir : la forme potentielle",
    minutes: 18,
    summary: "Dire ce qu'on sait ou peut faire (話せる, 食べられる), voir et entendre, et dire qu'on en est devenu capable.",
    sections: [
      {
        title: "Fabriquer la forme potentielle",
        formula: "Groupe 1 : son en u → [son en e + る]　Groupe 2 : る → [られる]　する → [できる]　来る → [来られる]",
        paragraphs: [
          "La forme potentielle dit ce qu'on **peut** ou **sait** faire. Groupe 1 : le dernier son passe en -e, puis る : 話す → 話[せる], 読む → 読[める], 泳ぐ → 泳[げる].",
          "Groupe 2 : る → [られる] (食べ[られる], 見[られる]). Irréguliers : する → [できる], 来る → [来られる] (こられる). Le résultat se conjugue comme un verbe du groupe 2 : 話せます, 話せない.",
        ],
        examples: [
          { ja: "漢字が少し読[めます]。", reading: "かんじがすこしよ[めます]。", romaji: "Kanji ga sukoshi yo[memasu].", fr: "Je sais lire un peu les kanji." },
          { ja: "辛い料理は食べ[られません]。", reading: "からいりょうりはたべ[られません]。", romaji: "Karai ryouri wa tabe[raremasen].", fr: "Je ne peux pas manger de plats épicés." },
          { ja: "日曜日に来[られます]か。", reading: "にちようびにこ[られます]か。", romaji: "Nichiyoubi ni ko[raremasu] ka.", fr: "Tu peux venir dimanche ?" },
        ],
        tip: "Avec la forme potentielle, l'objet prend souvent [が] au lieu de を : 日本語[が]話せます.",
      },
      {
        title: "La version longue : ～ことができる",
        formula: "Dictionnaire + [ことができます]　＝　forme potentielle, en plus formel",
        paragraphs: [
          "[～ことができる] a le même sens que la forme potentielle, en plus **formel** et plus long : 話す[ことができます] = 話せます. On le voit surtout à l'écrit, dans les règlements et les annonces.",
          "Au négatif : [ことができません] (« impossible », ou « ce n'est pas permis »).",
        ],
        examples: [
          { ja: "ここでカードを使う[ことができます]。", reading: "ここでカードをつかう[ことができます]。", romaji: "Koko de kaado o tsukau [koto ga dekimasu].", fr: "On peut payer par carte ici." },
          { ja: "このプールでは泳ぐ[ことができません]。", reading: "このプールではおよぐ[ことができません]。", romaji: "Kono puuru de wa oyogu [koto ga dekimasen].", fr: "On ne peut pas nager dans cette piscine." },
        ],
      },
      {
        title: "Voir, entendre, devenir capable",
        formula: "[見える] / [聞こえる] (se voir, s'entendre)　／　potentiel + [ようになる]",
        paragraphs: [
          "[見える] et [聞こえる] disent qu'une chose **se voit** ou **s'entend** d'elle-même : 窓から海が[見えます]. 見られる veut plutôt dire « avoir l'occasion de voir » : 映画館で映画が見られます.",
          "Pour un progrès : forme potentielle + [ようになりました] : 漢字が読める[ようになりました] (j'arrive maintenant à lire les kanji).",
        ],
        examples: [
          { ja: "部屋から富士山が[見えます]。", reading: "へやからふじさんが[みえます]。", romaji: "Heya kara Fujisan ga [miemasu].", fr: "On voit le mont Fuji depuis la chambre." },
          { ja: "音楽が[聞こえます]ね。", reading: "おんがくが[きこえます]ね。", romaji: "Ongaku ga [kikoemasu] ne.", fr: "On entend de la musique, hein." },
          { ja: "日本語が話せる[ようになりました]。", reading: "にほんごがはなせる[ようになりました]。", romaji: "Nihongo ga hanaseru [you ni narimashita].", fr: "Je suis maintenant capable de parler japonais." },
        ],
        tip: "À l'oral, on entend souvent 見れる ou 来れる (sans ら). C'est courant, mais à l'examen la forme correcte est [見られる].",
      },
    ],
    vocabulary: [
      { ja: "漢字", reading: "かんじ", fr: "kanji" },
      { ja: "英語", reading: "えいご", fr: "anglais (langue)" },
      { ja: "音楽", reading: "おんがく", fr: "musique" },
      { ja: "歌", reading: "うた", fr: "chanson" },
      { ja: "見える", reading: "みえる", fr: "se voir, être visible" },
      { ja: "聞こえる", reading: "きこえる", fr: "s'entendre, être audible" },
      { ja: "力", reading: "ちから", fr: "force" },
      { ja: "目", reading: "め", fr: "œil" },
    ],
    kanji: ["力", "字", "楽", "歌", "文", "漢", "目", "英", "音"],
    keyPoints: [
      "Potentiel : 話す → [話せる], 食べる → [食べられる], する → [できる], 来る → [来られる].",
      "Plus formel : dictionnaire + [ことができる].",
      "Se voir, s'entendre : [見える], [聞こえる] ; progrès : potentiel + [ようになる].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Je sais parler japonais.", answer: "日本語が話せます。", wrong: ["日本語が話られます。", "日本語が話さます。"] },
        { fr: "Je ne peux pas manger de viande.", answer: "肉が食べられません。", wrong: ["肉が食べかれません。", "肉が食べせません。"] },
        { fr: "Je sais nager.", answer: "泳げます。", wrong: ["泳ぎられます。", "泳がれます。"] },
        { fr: "Tu peux venir demain ?", answer: "明日来られますか。", wrong: ["明日来せますか。", "明日来できますか。"] },
        { fr: "Je sais lire les kanji.", answer: "漢字が読めます。", wrong: ["漢字が読みられます。", "漢字が読みます。"] },
        { fr: "Je ne sais pas conduire.", answer: "運転ができません。", wrong: ["運転がしません。", "運転をできるません。"] },
        { fr: "On voit la mer depuis la fenêtre.", answer: "窓から海が見えます。", wrong: ["窓から海が見ます。", "窓から海を見えます。"] },
        { fr: "On entend le chant d'un oiseau.", answer: "鳥の声が聞こえます。", wrong: ["鳥の声が聞きます。", "鳥の声を聞こえます。"] },
        { fr: "Je suis maintenant capable de lire le japonais.", answer: "日本語が読めるようになりました。", wrong: ["日本語が読めるようにしました。", "日本語が読めることになりました。"] },
        { fr: "On peut payer par carte ici.", answer: "ここでカードを使うことができます。", wrong: ["ここでカードを使うことがあります。", "ここでカードを使ったことができます。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Je sais nager.", answers: ["泳げます。", "およげます。"] },
        { fr: "Je sais parler anglais.", answers: ["英語が話せます。", "えいごがはなせます。"] },
        { fr: "Je ne peux pas manger.", answers: ["食べられません。", "たべられません。"] },
        { fr: "On voit la mer.", answers: ["海が見えます。", "うみがみえます。"] },
        { fr: "On entend de la musique.", answers: ["音楽が聞こえます。", "おんがくがきこえます。"] },
        { fr: "Je sais lire les kanji.", answers: ["漢字が読めます。", "かんじがよめます。"] },
      ],
    },
    morePractice: { href: "/exercices/grammaire?point=n4-koto-ga-dekiru", label: "Plus de phrases avec ～ことができる" },
  },
  {
    id: "n4-devoir-pouvoir",
    title: "Devoir ou pas : ～なければならない, ～なくてもいい",
    minutes: 15,
    summary: "Exprimer une obligation (« je dois »), la dire à l'oral, et dire qu'on n'est pas obligé.",
    sections: [
      {
        title: "« Je dois… » : ～なければなりません",
        formula: "Verbe en ない sans い + [ければなりません]",
        paragraphs: [
          "On part de la forme en ない, on retire le い final et on ajoute [ければなりません] : 行かない → 行かな[ければなりません], する → しな[ければなりません].",
          "C'est une obligation venue d'une règle ou de la situation : un travail, un rendez-vous, la santé.",
        ],
        examples: [
          { ja: "明日までに宿題をしな[ければなりません]。", reading: "あしたまでにしゅくだいをしな[ければなりません]。", romaji: "Ashita made ni shukudai o shina[kereba narimasen].", fr: "Je dois faire mes devoirs pour demain." },
          { ja: "毎日薬を飲まな[ければなりません]。", reading: "まいにちくすりをのまな[ければなりません]。", romaji: "Mainichi kusuri o noma[nakereba narimasen].", fr: "Je dois prendre un médicament tous les jours." },
        ],
        tip: "On garde la forme en ない entière jusqu'au な : 飲まな + ければ. Jamais 飲みなければ.",
      },
      {
        title: "À l'oral : ～ないといけない, ～なきゃ",
        formula: "Verbe en ない + [といけません]　／　familier : verbe en ない sans い + [きゃ]",
        paragraphs: [
          "[～ないといけません] a le même sens, en plus courant à l'oral : 病院に行かない[といけません].",
          "Entre amis, tout se raccourcit en [なきゃ] : 行かな[きゃ] ! (« il faut que j'y aille ! »).",
        ],
        examples: [
          { ja: "もう帰らない[といけません]。", reading: "もうかえらない[といけません]。", romaji: "Mou kaeranai [to ikemasen].", fr: "Je dois déjà rentrer." },
          { ja: "急がな[きゃ]！", reading: "いそがな[きゃ]！", romaji: "Isogana[kya]!", fr: "Il faut que je me dépêche ! (familier)" },
        ],
      },
      {
        title: "Pas besoin : ～なくてもいい",
        formula: "Verbe en ない sans い + [くてもいいです]",
        paragraphs: [
          "Forme en ない : い → [くてもいいです] : « pas besoin de… ». 来な[くてもいいです] (tu n'as pas besoin de venir).",
          "C'est la réponse négative à ～なければなりませんか : はい、～なければなりません / いいえ、～な[くてもいいです].",
        ],
        examples: [
          { ja: "明日は来な[くてもいいです]。", reading: "あしたはこな[くてもいいです]。", romaji: "Ashita wa kona[kute mo ii desu].", fr: "Tu n'as pas besoin de venir demain." },
          { ja: "靴を脱がな[くてもいいです]か。", reading: "くつをぬがな[くてもいいです]か。", romaji: "Kutsu o nugana[kute mo ii desu] ka.", fr: "Est-ce que je peux garder mes chaussures ?" },
        ],
        tip: "なくてもいい (pas obligé) n'est pas てはいけない (interdit) : 払わなくてもいい = c'est gratuit.",
      },
    ],
    vocabulary: [
      { ja: "規則", reading: "きそく", fr: "règle" },
      { ja: "準備", reading: "じゅんび", fr: "préparation" },
      { ja: "予約", reading: "よやく", fr: "réservation" },
      { ja: "払う", reading: "はらう", fr: "payer" },
      { ja: "急ぐ", reading: "いそぐ", fr: "se dépêcher" },
      { ja: "注意", reading: "ちゅうい", fr: "attention" },
      { ja: "病院", reading: "びょういん", fr: "hôpital" },
      { ja: "医者", reading: "いしゃ", fr: "médecin" },
    ],
    kanji: ["体", "医", "急", "止", "正", "注", "病", "者", "院"],
    keyPoints: [
      "Obligation : forme en ない sans い + [ければなりません] (行かなければなりません).",
      "À l'oral : [ないといけません] ; entre amis : [なきゃ].",
      "Pas besoin : forme en ない sans い + [くてもいいです].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Je dois partir tôt demain.", answer: "明日は早く出かけなければなりません。", wrong: ["明日は早く出かけなくてもいいです。", "明日は早く出かけないければなりません。"] },
        { fr: "Il faut payer ici.", answer: "ここで払わなければなりません。", wrong: ["ここで払あなければなりません。", "ここで払わなくてもいいです。"] },
        { fr: "Je dois réserver l'hôtel.", answer: "ホテルを予約しなければなりません。", wrong: ["ホテルを予約さなければなりません。", "ホテルを予約しないければなりません。"] },
        { fr: "Il faut se dépêcher !", answer: "急がなければなりません。", wrong: ["急ぎなければなりません。", "急がないでなりません。"] },
        { fr: "Je dois aller à l'hôpital.", answer: "病院に行かないといけません。", wrong: ["病院に行かないといいです。", "病院に行かなくていけません。"] },
        { fr: "Il faut que j'y aille ! (familier)", answer: "行かなきゃ。", wrong: ["行きなきゃ。", "行くなきゃ。"] },
        { fr: "Tu n'as pas besoin de venir demain.", answer: "明日は来なくてもいいです。", wrong: ["明日は来てはいけません。", "明日は来なければなりません。"] },
        { fr: "Pas besoin d'enlever tes chaussures.", answer: "靴を脱がなくてもいいです。", wrong: ["靴を脱いではいけません。", "靴を脱がないくてもいいです。"] },
        { fr: "Je dois prendre un médicament.", answer: "薬を飲まなければなりません。", wrong: ["薬を飲みなければなりません。", "薬を飲まなくてもいいです。"] },
        { fr: "Dois-je écrire mon nom ? — Non, pas besoin.", answer: "いいえ、書かなくてもいいです。", wrong: ["いいえ、書いてはいけません。", "いいえ、書かなければなりません。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Je dois y aller.", answers: ["行かなければなりません。", "いかなければなりません。", "行かないといけません。", "いかないといけません。"] },
        { fr: "Tu n'as pas besoin de venir.", answers: ["来なくてもいいです。", "こなくてもいいです。"] },
        { fr: "Je dois travailler.", answers: ["働かなければなりません。", "はたらかなければなりません。", "働かないといけません。", "はたらかないといけません。"] },
        { fr: "Pas besoin de payer.", answers: ["払わなくてもいいです。", "はらわなくてもいいです。"] },
        { fr: "Je dois me dépêcher.", answers: ["急がなければなりません。", "いそがなければなりません。", "急がないといけません。", "いそがないといけません。"] },
        { fr: "Il faut que j'y aille ! (familier)", answers: ["行かなきゃ。", "いかなきゃ。"] },
      ],
    },
    morePractice: { href: "/exercices/grammaire?point=n4-nakereba-naranai", label: "Plus de phrases avec ～なければならない" },
  },
  {
    id: "n4-transitifs",
    title: "Ouvrir ou s'ouvrir : transitifs, intransitifs, ～ている, ～てある",
    minutes: 18,
    summary: "Les paires de verbes (開ける / 開く), décrire un état (開いている) et un état préparé exprès (開けてある).",
    sections: [
      {
        title: "Deux verbes pour une même action",
        formula: "Quelqu'un + [を] + 開ける (ouvrir)　／　chose + [が] + 開く (s'ouvrir)",
        paragraphs: [
          "Beaucoup de verbes vont **par paires** : l'un dit qu'on **fait** l'action sur quelque chose (transitif, avec [を]), l'autre que la chose **se fait** (intransitif, avec [が]).",
          "開ける / 開く (ouvrir / s'ouvrir), 閉める / 閉まる (fermer / se fermer), 始める / 始まる (commencer), 止める / 止まる (arrêter / s'arrêter), 集める / 集まる (rassembler / se rassembler).",
        ],
        examples: [
          { ja: "窓[を開けます]。", reading: "まど[をあけます]。", romaji: "Mado [o akemasu].", fr: "J'ouvre la fenêtre." },
          { ja: "ドア[が開きました]。", reading: "ドア[があきました]。", romaji: "Doa [ga akimashita].", fr: "La porte s'est ouverte." },
          { ja: "授業[が始まります]。", reading: "じゅぎょう[がはじまります]。", romaji: "Jugyou [ga hajimarimasu].", fr: "Le cours commence." },
        ],
        tip: "Le transitif prend [を], l'intransitif [が] : 授業を始まります est faux.",
      },
      {
        title: "Un état qui reste : intransitif + ～ている",
        formula: "Chose + が + intransitif en て + [います]",
        paragraphs: [
          "Avec un verbe intransitif, ～ています décrit **l'état** qui résulte de l'action : 窓が開[いています] (la fenêtre est ouverte).",
          "De même : 電気がつ[いています] (la lumière est allumée), 時計が止ま[っています] (la montre est arrêtée). Avec 着る : シャツを着[ています] (je porte une chemise).",
        ],
        examples: [
          { ja: "窓が開[いています]。", reading: "まどがあ[いています]。", romaji: "Mado ga a[ite imasu].", fr: "La fenêtre est ouverte." },
          { ja: "時計が止ま[っています]。", reading: "とけいがとま[っています]。", romaji: "Tokei ga toma[tte imasu].", fr: "La montre est arrêtée." },
          { ja: "赤いシャツを着[ています]。", reading: "あかいシャツをき[ています]。", romaji: "Akai shatsu o ki[te imasu].", fr: "Il porte une chemise rouge." },
        ],
        tip: "着ています veut presque toujours dire « porter » (un vêtement), pas « être en train de s'habiller ».",
      },
      {
        title: "Préparé exprès : transitif + ～てある",
        formula: "Chose + が + transitif en て + [あります]",
        paragraphs: [
          "Avec un verbe **transitif**, [～てあります] décrit un état laissé **exprès** par quelqu'un : 窓が開け[てあります] (quelqu'un l'a ouverte, pour aérer).",
          "Comparer : 窓が開いています (elle est ouverte, simple constat) et 窓が開け[てあります] (on l'a ouverte exprès).",
        ],
        examples: [
          { ja: "壁に地図が貼[ってあります]。", reading: "かべにちずがは[ってあります]。", romaji: "Kabe ni chizu ga ha[tte arimasu].", fr: "Une carte est affichée au mur." },
          { ja: "ビールが冷や[してあります]よ。", reading: "ビールがひや[してあります]よ。", romaji: "Biiru ga hiya[shite arimasu] yo.", fr: "La bière est au frais (je l'y ai mise)." },
          { ja: "ここに名前が書[いてあります]。", reading: "ここになまえがか[いてあります]。", romaji: "Koko ni namae ga ka[ite arimasu].", fr: "Le nom est écrit ici." },
        ],
        tip: "Avec ～てある, la chose prend [が] (ou は), plus を.",
      },
    ],
    vocabulary: [
      { ja: "開く", reading: "あく", fr: "s'ouvrir" },
      { ja: "閉まる", reading: "しまる", fr: "se fermer" },
      { ja: "始まる", reading: "はじまる", fr: "commencer (intransitif)" },
      { ja: "止まる", reading: "とまる", fr: "s'arrêter" },
      { ja: "集まる", reading: "あつまる", fr: "se rassembler" },
      { ja: "着る", reading: "きる", fr: "porter, mettre (un vêtement)" },
      { ja: "動く", reading: "うごく", fr: "bouger, fonctionner" },
      { ja: "洋服", reading: "ようふく", fr: "vêtements" },
    ],
    kanji: ["切", "動", "始", "服", "着", "立", "終", "起", "開", "集"],
    keyPoints: [
      "Transitif + [を] (開ける) ; intransitif + [が] (開く).",
      "État constaté : intransitif + [ています] (窓が開いています).",
      "État préparé exprès : transitif + [てあります] (窓が開けてあります).",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "J'ouvre la fenêtre.", answer: "窓を開けます。", wrong: ["窓が開けます。", "窓を開きます。"] },
        { fr: "La porte s'est ouverte.", answer: "ドアが開きました。", wrong: ["ドアを開きました。", "ドアが開けました。"] },
        { fr: "Le cours commence à 9 h.", answer: "授業は九時に始まります。", wrong: ["授業は九時に始めます。", "授業を九時に始まります。"] },
        { fr: "La fenêtre est ouverte.", answer: "窓が開いています。", wrong: ["窓が開けています。", "窓を開いています。"] },
        { fr: "La montre est arrêtée.", answer: "時計が止まっています。", wrong: ["時計が止めています。", "時計を止まっています。"] },
        { fr: "Il porte une chemise blanche.", answer: "白いシャツを着ています。", wrong: ["白いシャツが着ています。", "白いシャツを着てあります。"] },
        { fr: "La bière est au frais (je l'y ai mise).", answer: "ビールが冷やしてあります。", wrong: ["ビールが冷やしています。", "ビールが冷えてあります。"] },
        { fr: "Le nom est écrit ici.", answer: "ここに名前が書いてあります。", wrong: ["ここに名前が書いています。", "ここに名前が書けてあります。"] },
        { fr: "Les étudiants se sont rassemblés.", answer: "学生が集まりました。", wrong: ["学生が集めました。", "学生を集まりました。"] },
        { fr: "J'ai arrêté la voiture.", answer: "車を止めました。", wrong: ["車が止めました。", "車を止まりました。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "J'ouvre la fenêtre.", answers: ["窓を開けます。", "まどをあけます。"] },
        { fr: "La porte est ouverte.", answers: ["ドアが開いています。", "ドアがあいています。"] },
        { fr: "Le cours commence.", answers: ["授業が始まります。", "じゅぎょうがはじまります。"] },
        { fr: "La fenêtre est fermée.", answers: ["窓が閉まっています。", "まどがしまっています。"] },
        { fr: "Le nom est écrit.", answers: ["名前が書いてあります。", "なまえがかいてあります。"] },
        { fr: "Je porte une chemise.", answers: ["シャツを着ています。", "シャツをきています。"] },
      ],
    },
  },
  {
    id: "n4-passif",
    title: "Le passif : ほめられる, 盗まれる",
    minutes: 18,
    summary: "Fabriquer le passif, dire qu'on a subi quelque chose de gênant, et décrire ce qui a été fait.",
    sections: [
      {
        title: "Fabriquer le passif",
        formula: "Groupe 1 : son en u → [son en a + れる]　Groupe 2 : る → [られる]　する → [される]　来る → [来られる]",
        paragraphs: [
          "Le passif dit ce qu'on **subit** : 先生にほめ[られました] (j'ai été félicité·e par le professeur). Celui qui fait l'action prend [に].",
          "Groupe 1 : son en -a + れる : 読む → 読[まれる], 書く → 書[かれる], 言う → 言[われる]. Groupe 2 : る → [られる], comme le potentiel. する → [される], 来る → [来られる].",
        ],
        examples: [
          { ja: "先生にほめ[られました]。", reading: "せんせいにほめ[られました]。", romaji: "Sensei ni home[raremashita].", fr: "J'ai été félicité·e par le professeur." },
          { ja: "母に叱[られました]。", reading: "ははにしか[られました]。", romaji: "Haha ni shika[raremashita].", fr: "Je me suis fait gronder par ma mère." },
          { ja: "犬にかま[れました]。", reading: "いぬにかま[れました]。", romaji: "Inu ni kama[remashita].", fr: "Je me suis fait mordre par un chien." },
        ],
        tip: "Groupe 2 : passif et potentiel ont la même forme (食べられる). Le sens se devine avec に (passif) ou が (potentiel).",
      },
      {
        title: "Le passif qui gêne",
        formula: "Personne + [に] + objet + [を] + verbe au passif",
        paragraphs: [
          "Le japonais utilise beaucoup le passif pour dire qu'on a été **gêné** par l'action de quelqu'un : 弟[に]ケーキ[を]食べられました (mon petit frère m'a mangé mon gâteau).",
          "Même un verbe sans objet peut se mettre au passif pour exprimer la gêne : 雨に降られました (je me suis fait surprendre par la pluie).",
        ],
        examples: [
          { ja: "電車で足を踏ま[れました]。", reading: "でんしゃであしをふま[れました]。", romaji: "Densha de ashi o fuma[remashita].", fr: "Quelqu'un m'a marché sur le pied dans le train." },
          { ja: "猫に魚を食べ[られました]。", reading: "ねこにさかなをたべ[られました]。", romaji: "Neko ni sakana o tabe[raremashita].", fr: "Le chat m'a mangé mon poisson." },
          { ja: "雨に降[られました]。", reading: "あめにふ[られました]。", romaji: "Ame ni fu[raremashita].", fr: "Je me suis fait surprendre par la pluie." },
        ],
        tip: "Ce qu'on a perdu garde [を] : 財布[を]盗まれました (on m'a volé mon portefeuille).",
      },
      {
        title: "Dire ce qui a été fait",
        formula: "Chose + は / が + verbe au passif",
        paragraphs: [
          "Pour des faits généraux, on utilise le passif sans dire qui : このお寺は八百年前に建て[られました].",
          "C'est fréquent dans les informations et les explications : この車は日本で作[られています].",
        ],
        examples: [
          { ja: "このお寺は八百年前に建て[られました]。", reading: "このおてらははっぴゃくねんまえにたて[られました]。", romaji: "Kono otera wa happyaku nen mae ni tate[raremashita].", fr: "Ce temple a été construit il y a huit cents ans." },
          { ja: "この本は多くの人に読ま[れています]。", reading: "このほんはおおくのひとによま[れています]。", romaji: "Kono hon wa ooku no hito ni yoma[rete imasu].", fr: "Ce livre est lu par beaucoup de gens." },
          { ja: "この車は日本で作[られています]。", reading: "このくるまはにほんでつく[られています]。", romaji: "Kono kuruma wa Nihon de tsuku[rarete imasu].", fr: "Cette voiture est fabriquée au Japon." },
        ],
      },
    ],
    vocabulary: [
      { ja: "叱る", reading: "しかる", fr: "gronder" },
      { ja: "褒める", reading: "ほめる", fr: "féliciter, complimenter" },
      { ja: "盗む", reading: "ぬすむ", fr: "voler (dérober)" },
      { ja: "踏む", reading: "ふむ", fr: "marcher sur" },
      { ja: "建てる", reading: "たてる", fr: "construire" },
      { ja: "作る", reading: "つくる", fr: "fabriquer, préparer" },
      { ja: "使う", reading: "つかう", fr: "utiliser" },
      { ja: "出発", reading: "しゅっぱつ", fr: "départ" },
    ],
    kanji: ["作", "使", "写", "建", "犬", "発", "魚", "鳥"],
    keyPoints: [
      "Passif : 読む → [読まれる], 食べる → [食べられる], する → [される], 来る → [来られる].",
      "Celui qui agit prend [に] ; ce qu'on perd garde [を] (財布を盗まれました).",
      "Faits généraux : chose + は + passif (建てられました, 作られています).",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "J'ai été félicité·e par le professeur.", answer: "先生にほめられました。", wrong: ["先生がほめられました。", "先生にほめました。"] },
        { fr: "Je me suis fait gronder par ma mère.", answer: "母に叱られました。", wrong: ["母を叱られました。", "母に叱りました。"] },
        { fr: "On m'a volé mon portefeuille.", answer: "財布を盗まれました。", wrong: ["財布が盗みました。", "財布を盗まられました。"] },
        { fr: "Mon petit frère m'a mangé mon gâteau.", answer: "弟にケーキを食べられました。", wrong: ["弟がケーキを食べられました。", "弟にケーキを食べさせました。"] },
        { fr: "Je me suis fait surprendre par la pluie.", answer: "雨に降られました。", wrong: ["雨が降られました。", "雨に降りました。"] },
        { fr: "Ce temple a été construit il y a 500 ans.", answer: "このお寺は五百年前に建てられました。", wrong: ["このお寺は五百年前に建てました。", "このお寺は五百年前に建たれました。"] },
        { fr: "On m'a demandé mon nom.", answer: "名前を聞かれました。", wrong: ["名前を聞きられました。", "名前を聞かせました。"] },
        { fr: "Quelqu'un m'a marché sur le pied.", answer: "足を踏まれました。", wrong: ["足を踏みられました。", "足が踏みました。"] },
        { fr: "Ce livre est lu dans le monde entier.", answer: "この本は世界中で読まれています。", wrong: ["この本は世界中で読めています。", "この本は世界中で読ませています。"] },
        { fr: "J'ai été invité·e par un ami.", answer: "友達に招待されました。", wrong: ["友達に招待させました。", "友達を招待されました。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "J'ai été félicité·e.", answers: ["ほめられました。", "褒められました。"] },
        { fr: "On m'a volé mon portefeuille.", answers: ["財布を盗まれました。", "さいふをぬすまれました。"] },
        { fr: "Je me suis fait gronder.", answers: ["叱られました。", "しかられました。"] },
        { fr: "Je me suis fait mordre par un chien.", answers: ["犬にかまれました。", "いぬにかまれました。"] },
        { fr: "Je me suis fait surprendre par la pluie.", answers: ["雨に降られました。", "あめにふられました。"] },
        { fr: "Cette voiture est fabriquée au Japon.", answers: ["この車は日本で作られています。", "このくるまはにほんでつくられています。"] },
      ],
    },
  },
  {
    id: "n4-causatif",
    title: "Faire faire et laisser faire : le causatif",
    minutes: 15,
    summary: "Faire faire quelque chose à quelqu'un, le laisser faire, et demander poliment « laissez-moi… ».",
    sections: [
      {
        title: "Fabriquer le causatif",
        formula: "Groupe 1 : son en u → [son en a + せる]　Groupe 2 : る → [させる]　する → [させる]　来る → [来させる]",
        paragraphs: [
          "Le causatif dit qu'on **fait faire** une action à quelqu'un : 子どもに野菜を食べ[させます] (je fais manger des légumes à mon enfant).",
          "Groupe 1 : 読む → 読[ませる], 行く → 行[かせる], 書く → 書[かせる]. Groupe 2 : る → [させる]. する → [させる], 来る → [来させる] (こさせる).",
        ],
        examples: [
          { ja: "先生は学生に作文を書[かせました]。", reading: "せんせいはがくせいにさくぶんをか[かせました]。", romaji: "Sensei wa gakusei ni sakubun o ka[kasemashita].", fr: "Le professeur a fait écrire une rédaction aux étudiants." },
          { ja: "母は弟に部屋を掃除[させました]。", reading: "はははおとうとにへやをそうじ[させました]。", romaji: "Haha wa otouto ni heya o souji [sasemashita].", fr: "Ma mère a fait ranger sa chambre à mon petit frère." },
        ],
        tip: "Celui qu'on fait agir prend [に] quand il y a déjà un objet en を : 学生[に]作文を書かせる.",
      },
      {
        title: "Laisser faire",
        formula: "Personne + [を] (ou に) + causatif",
        paragraphs: [
          "Le causatif peut aussi vouloir dire **laisser faire** : 子どもを公園で遊ば[せます] (je laisse les enfants jouer au parc).",
          "Avec un verbe sans objet, la personne prend souvent [を] : 学生[を]帰らせました (j'ai laissé rentrer les étudiants).",
        ],
        examples: [
          { ja: "子どもを自由に遊ば[せました]。", reading: "こどもをじゆうにあそば[せました]。", romaji: "Kodomo o jiyuu ni asoba[semashita].", fr: "J'ai laissé les enfants jouer librement." },
          { ja: "先生は学生を早く帰ら[せました]。", reading: "せんせいはがくせいをはやくかえら[せました]。", romaji: "Sensei wa gakusei o hayaku kaera[semashita].", fr: "Le professeur a laissé les étudiants rentrer tôt." },
        ],
      },
      {
        title: "« Laissez-moi… » : ～させてください",
        formula: "Causatif en て + [ください]",
        paragraphs: [
          "[～させてください] = « laissez-moi faire… », une demande polie et motivée : 私に説明さ[せてください] (laissez-moi expliquer).",
          "Pour annoncer poliment qu'on aimerait partir : 今日は早く帰ら[せてください].",
        ],
        examples: [
          { ja: "この仕事は私にやら[せてください]。", reading: "このしごとはわたしにやら[せてください]。", romaji: "Kono shigoto wa watashi ni yara[sete kudasai].", fr: "Laissez-moi m'occuper de ce travail." },
          { ja: "少し考え[させてください]。", reading: "すこしかんがえ[させてください]。", romaji: "Sukoshi kangae[sasete kudasai].", fr: "Laissez-moi réfléchir un peu." },
        ],
        tip: "Ne confonds pas 休ませてください (laissez-moi me reposer) et 休んでください (reposez-vous).",
      },
    ],
    vocabulary: [
      { ja: "習う", reading: "ならう", fr: "apprendre (avec quelqu'un)" },
      { ja: "勉強", reading: "べんきょう", fr: "études" },
      { ja: "試験", reading: "しけん", fr: "examen" },
      { ja: "問題", reading: "もんだい", fr: "problème, question d'examen" },
      { ja: "質問", reading: "しつもん", fr: "question" },
      { ja: "答える", reading: "こたえる", fr: "répondre" },
      { ja: "教える", reading: "おしえる", fr: "enseigner" },
      { ja: "強い", reading: "つよい", fr: "fort" },
    ],
    kanji: ["勉", "問", "強", "教", "習", "答", "試", "質", "題", "験"],
    keyPoints: [
      "Causatif : 読む → [読ませる], 食べる → [食べさせる], する → [させる], 来る → [来させる].",
      "Faire faire : personne + [に] + objet + を ; laisser faire : personne + [を].",
      "« Laissez-moi… » : causatif en て + [ください].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Le professeur a fait lire le livre aux étudiants.", answer: "先生は学生に本を読ませました。", wrong: ["先生は学生に本を読まれました。", "先生は学生に本を読みさせました。"] },
        { fr: "Ma mère m'a fait manger des légumes.", answer: "母は私に野菜を食べさせました。", wrong: ["母は私に野菜を食べられました。", "母は私に野菜を食べせました。"] },
        { fr: "Le professeur a fait répondre les étudiants.", answer: "先生は学生に答えさせました。", wrong: ["先生は学生に答えられました。", "先生は学生に答えせました。"] },
        { fr: "J'ai laissé les enfants jouer.", answer: "子どもを遊ばせました。", wrong: ["子どもを遊ばれました。", "子どもを遊びさせました。"] },
        { fr: "Laissez-moi réfléchir un peu.", answer: "少し考えさせてください。", wrong: ["少し考えてください。", "少し考えられてください。"] },
        { fr: "Laissez-moi rentrer tôt aujourd'hui.", answer: "今日は早く帰らせてください。", wrong: ["今日は早く帰ってください。", "今日は早く帰させてください。"] },
        { fr: "Je fais étudier mon fils tous les jours.", answer: "毎日息子に勉強させます。", wrong: ["毎日息子に勉強されます。", "毎日息子に勉強しさせます。"] },
        { fr: "Laissez-moi poser une question.", answer: "質問させてください。", wrong: ["質問してください。", "質問されてください。"] },
        { fr: "Mon père m'a fait aller au magasin.", answer: "父は私を店に行かせました。", wrong: ["父は私を店に行かれました。", "父は私を店に行きさせました。"] },
        { fr: "Désolé·e de vous avoir fait attendre.", answer: "お待たせしました。", wrong: ["お待ちしました。", "お待たれしました。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Laissez-moi réfléchir.", answers: ["考えさせてください。", "かんがえさせてください。"] },
        { fr: "Laissez-moi poser une question.", answers: ["質問させてください。", "しつもんさせてください。"] },
        { fr: "J'ai fait manger des légumes à mon enfant.", answers: ["子どもに野菜を食べさせました。", "こどもにやさいをたべさせました。", "子供に野菜を食べさせました。"] },
        { fr: "Désolé·e de vous avoir fait attendre.", answers: ["お待たせしました。", "おまたせしました。"] },
        { fr: "Le professeur a fait lire les étudiants.", answers: ["先生は学生に読ませました。", "せんせいはがくせいによませました。"] },
        { fr: "Laissez-moi rentrer.", answers: ["帰らせてください。", "かえらせてください。"] },
      ],
    },
  },
  {
    id: "n4-composes",
    title: "Verbes composés : ～やすい, ～にくい, ～方, ～始める",
    minutes: 15,
    summary: "Dire qu'une chose est facile ou difficile à faire, parler de la façon de faire, et commencer, finir ou continuer.",
    sections: [
      {
        title: "Facile ou difficile à faire",
        formula: "Verbe en ます sans ます + [やすい] / [にくい]",
        paragraphs: [
          "Verbe sans ます + [やすい] : « facile à… » ; + [にくい] : « difficile à… ». 読み[やすい]本, 食べ[にくい]料理. Le tout se conjugue comme un adjectif en い.",
        ],
        examples: [
          { ja: "この本は字が大きくて読み[やすい]です。", reading: "このほんはじがおおきくてよみ[やすい]です。", romaji: "Kono hon wa ji ga ookikute yomi[yasui] desu.", fr: "Ce livre a de gros caractères : il est facile à lire." },
          { ja: "この肉は硬くて食べ[にくい]です。", reading: "このにくはかたくてたべ[にくい]です。", romaji: "Kono niku wa katakute tabe[nikui] desu.", fr: "Cette viande est dure : elle est difficile à manger." },
        ],
        tip: "やすい (facile à) n'est pas 安い (bon marché) : 読みやすい n'a rien à voir avec le prix.",
      },
      {
        title: "La façon de faire : ～方",
        formula: "Verbe en ます sans ます + [方] (かた)",
        paragraphs: [
          "[方] transforme le verbe en nom : 作り[方] (la façon de préparer), 使い[方] (le mode d'emploi), 読み[方] (la lecture d'un kanji).",
          "L'objet prend alors [の] au lieu de を : カレー[の]作り方.",
        ],
        examples: [
          { ja: "すしの作り[方]を教えてください。", reading: "すしのつくり[かた]をおしえてください。", romaji: "Sushi no tsukuri[kata] o oshiete kudasai.", fr: "Apprends-moi à faire des sushis." },
          { ja: "この漢字の読み[方]がわかりません。", reading: "このかんじのよみ[かた]がわかりません。", romaji: "Kono kanji no yomi[kata] ga wakarimasen.", fr: "Je ne sais pas comment se lit ce kanji." },
        ],
        tip: "Avec ～方, l'objet prend の : すし[の]作り方, pas すしを作り方.",
      },
      {
        title: "Commencer, finir, continuer",
        formula: "Verbe en ます sans ます + [始める] / [終わる] / [続ける]",
        paragraphs: [
          "Verbe sans ます + [始める] : se mettre à… ; + [終わる] : finir de… ; + [続ける] : continuer à… 雨が降り[始めました], 本を読み[終わりました].",
        ],
        examples: [
          { ja: "雨が降り[始めました]。", reading: "あめがふり[はじめました]。", romaji: "Ame ga furi[hajimemashita].", fr: "Il s'est mis à pleuvoir." },
          { ja: "ご飯を食べ[終わったら]、お茶を飲みましょう。", reading: "ごはんをたべ[おわったら]、おちゃをのみましょう。", romaji: "Gohan o tabe[owattara], ocha o nomimashou.", fr: "Quand on aura fini de manger, buvons un thé." },
          { ja: "三時間歩き[続けました]。", reading: "さんじかんあるき[つづけました]。", romaji: "Sanjikan aruki[tsuzukemashita].", fr: "J'ai marché trois heures sans m'arrêter." },
        ],
      },
    ],
    vocabulary: [
      { ja: "料理", reading: "りょうり", fr: "cuisine, plat" },
      { ja: "野菜", reading: "やさい", fr: "légume" },
      { ja: "牛肉", reading: "ぎゅうにく", fr: "bœuf (viande)" },
      { ja: "お茶", reading: "おちゃ", fr: "thé" },
      { ja: "ご飯", reading: "ごはん", fr: "riz, repas" },
      { ja: "飲み物", reading: "のみもの", fr: "boisson" },
      { ja: "続ける", reading: "つづける", fr: "continuer" },
      { ja: "始める", reading: "はじめる", fr: "commencer" },
    ],
    kanji: ["料", "方", "牛", "理", "肉", "茶", "野", "飯", "飲"],
    keyPoints: [
      "Facile à : verbe sans ます + [やすい] ; difficile à : + [にくい].",
      "La façon de : verbe sans ます + [方] ; l'objet prend [の].",
      "Se mettre à, finir de, continuer à : + [始める] / [終わる] / [続ける].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Ce livre est facile à lire.", answer: "この本は読みやすいです。", wrong: ["この本は読むやすいです。", "この本は読みにくいです。"] },
        { fr: "Ces chaussures ne sont pas pratiques pour marcher.", answer: "この靴は歩きにくいです。", wrong: ["この靴は歩くにくいです。", "この靴は歩きやすいです。"] },
        { fr: "Apprends-moi à faire des sushis.", answer: "すしの作り方を教えてください。", wrong: ["すしを作り方を教えてください。", "すしの作る方を教えてください。"] },
        { fr: "Je ne sais pas utiliser ce téléphone.", answer: "この電話の使い方がわかりません。", wrong: ["この電話の使う方がわかりません。", "この電話を使い方がわかりません。"] },
        { fr: "Il s'est mis à pleuvoir.", answer: "雨が降り始めました。", wrong: ["雨が降る始めました。", "雨が降って始めました。"] },
        { fr: "J'ai fini de lire ce livre.", answer: "この本を読み終わりました。", wrong: ["この本を読む終わりました。", "この本を読み始めました。"] },
        { fr: "J'ai continué à marcher.", answer: "歩き続けました。", wrong: ["歩く続けました。", "歩いて続けました。"] },
        { fr: "Ce kanji est difficile à écrire.", answer: "この漢字は書きにくいです。", wrong: ["この漢字は書くにくいです。", "この漢字は書きやすいです。"] },
        { fr: "Comment se lit ce kanji ?", answer: "この漢字の読み方は何ですか。", wrong: ["この漢字の読む方は何ですか。", "この漢字を読み方は何ですか。"] },
        { fr: "Ce plat est facile à préparer.", answer: "この料理は作りやすいです。", wrong: ["この料理は作るやすいです。", "この料理は作りにくいです。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "C'est facile à lire.", answers: ["読みやすいです。", "よみやすいです。"] },
        { fr: "C'est difficile à manger.", answers: ["食べにくいです。", "たべにくいです。"] },
        { fr: "Apprenez-moi le mode d'emploi.", answers: ["使い方を教えてください。", "つかいかたをおしえてください。"] },
        { fr: "Il s'est mis à pleuvoir.", answers: ["雨が降り始めました。", "あめがふりはじめました。"] },
        { fr: "J'ai fini de manger.", answers: ["食べ終わりました。", "たべおわりました。"] },
        { fr: "J'ai continué à étudier.", answers: ["勉強し続けました。", "べんきょうしつづけました。"] },
      ],
    },
  },
];
