import type { Lesson } from "@/lib/course/lessons";

// Cours N4, partie 1 « Parler naturellement » : style familier et ～んです,
// expériences et conseils, avis et citations, projets et intentions.
export const N4_PARLER_LESSONS: Omit<Lesson, "number">[] = [
  {
    id: "n4-style-familier",
    title: "Parler entre amis : le style familier et ～んです",
    minutes: 18,
    summary: "Passer du style poli au style familier (だ, じゃない, だった), poser une question entre amis, et expliquer avec ～んです.",
    sections: [
      {
        title: "Noms et adjectifs en style familier",
        formula: "です → [だ]　じゃありません → [じゃない]　でした → [だった]　／　高いです → [高い]",
        paragraphs: [
          "Entre amis ou en famille, on laisse tomber です et ます. Pour un nom ou un adjectif en な, です devient [だ] : 学生[だ], 静か[だ]. Négatif : [じゃない] ; passé : [だった] ; passé négatif : [じゃなかった].",
          "Pour un adjectif en い, on retire simplement です : 高いです → 高い, 高かったです → 高かった. Les verbes prennent les formes simples vues au N5 (行く, 行かない, 行った).",
        ],
        examples: [
          { ja: "兄は大学生[だ]。", reading: "あにはだいがくせい[だ]。", romaji: "Ani wa daigakusei [da].", fr: "Mon grand frère est étudiant (familier)." },
          { ja: "昨日は暇[じゃなかった]。", reading: "きのうはひま[じゃなかった]。", romaji: "Kinou wa hima [ja nakatta].", fr: "Hier, je n'étais pas libre (familier)." },
          { ja: "その映画、おもしろ[かった]。", reading: "そのえいが、おもしろ[かった]。", romaji: "Sono eiga, omoshiro[katta].", fr: "Ce film était intéressant (familier)." },
        ],
        tip: "Jamais de だ après un adjectif en い : 高いだ est faux, on dit [高い].",
      },
      {
        title: "Poser une question entre amis",
        formula: "Intonation montante, ou [の]？ (sans か)　／　nom ou な + [なの]？",
        paragraphs: [
          "En style familier, か à la fin sonne brusque. On pose la question avec l'**intonation** : 行く？ (tu y vas ?), ou avec [の] : 行く[の]？ (plus doux, on attend une explication).",
          "Avec un nom ou un adjectif en な, だ disparaît devant の et devient [な] : 学生[なの]？ 暇[なの]？",
        ],
        examples: [
          { ja: "明日、来る[の]？", reading: "あした、くる[の]？", romaji: "Ashita, kuru [no]?", fr: "Tu viens demain ?" },
          { ja: "どうした[の]？", reading: "どうした[の]？", romaji: "Dou shita [no]?", fr: "Qu'est-ce qui t'arrive ?" },
          { ja: "妹さん、学生[なの]？", reading: "いもうとさん、がくせい[なの]？", romaji: "Imouto-san, gakusei [na no]?", fr: "Ta petite sœur est étudiante ?" },
        ],
        tip: "À l'oral, les particules は, を et が tombent souvent : ご飯、食べた？ (tu as mangé ?).",
      },
      {
        title: "Expliquer : ～んです",
        formula: "Forme familière + [んです]　／　nom ou な + [なんです]",
        paragraphs: [
          "[～んです] (à l'écrit のです) ajoute une nuance d'**explication** : on donne la raison d'une situation, ou on demande des explications. 頭が痛い[んです] = « c'est que j'ai mal à la tête ».",
          "Pour demander pourquoi : どうして来なかった[んですか]. Pour introduire une demande : 駅に行きたい[んですが]… (je voudrais aller à la gare, alors…).",
        ],
        examples: [
          { ja: "すみません、電車が止まった[んです]。", reading: "すみません、でんしゃがとまった[んです]。", romaji: "Sumimasen, densha ga tomatta [n desu].", fr: "Désolé·e, c'est que le train s'est arrêté." },
          { ja: "どうして食べない[んですか]。", reading: "どうしてたべない[んですか]。", romaji: "Doushite tabenai [n desu ka].", fr: "Pourquoi tu ne manges pas ?" },
          { ja: "駅に行きたい[んですが]、道を教えてください。", reading: "えきにいきたい[んですが]、みちをおしえてください。", romaji: "Eki ni ikitai [n desu ga], michi o oshiete kudasai.", fr: "Je voudrais aller à la gare : pouvez-vous m'indiquer le chemin ?" },
        ],
        tip: "Avec un nom ou un adjectif en な : 休み[なんです], 好き[なんです], jamais 休みだんです.",
      },
    ],
    vocabulary: [
      { ja: "兄", reading: "あに", fr: "(mon) grand frère" },
      { ja: "弟", reading: "おとうと", fr: "(mon) petit frère" },
      { ja: "姉", reading: "あね", fr: "(ma) grande sœur" },
      { ja: "妹", reading: "いもうと", fr: "(ma) petite sœur" },
      { ja: "家族", reading: "かぞく", fr: "famille" },
      { ja: "両親", reading: "りょうしん", fr: "parents" },
      { ja: "頭", reading: "あたま", fr: "tête" },
      { ja: "住所", reading: "じゅうしょ", fr: "adresse" },
    ],
    kanji: ["私", "兄", "弟", "姉", "妹", "親", "家", "族", "住"],
    keyPoints: [
      "Familier : [だ / じゃない / だった / じゃなかった] ; adjectif en い sans です.",
      "Question familière : intonation, ou [の]？ (学生[なの]？).",
      "Explication : forme familière + [んです] ; nom ou な + [なんです].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Mon grand frère est étudiant (familier).", answer: "兄は学生だ。", wrong: ["兄は学生じゃない。", "兄は学生だった。"] },
        { fr: "Ce n'était pas cher (familier).", answer: "高くなかった。", wrong: ["高いじゃなかった。", "高くなかっただ。"] },
        { fr: "C'était calme (familier).", answer: "静かだった。", wrong: ["静かかった。", "静かった。"] },
        { fr: "C'est délicieux (familier).", answer: "おいしい。", wrong: ["おいしいだ。", "おいしだ。"] },
        { fr: "Tu viens demain ? (familier)", answer: "明日、来るの？", wrong: ["明日、来るのだ？", "明日、来たの？"] },
        { fr: "Ta petite sœur est étudiante ? (familier)", answer: "妹さん、学生なの？", wrong: ["妹さん、学生だの？", "妹さん、学生の？"] },
        { fr: "C'est que j'ai mal à la tête.", answer: "頭が痛いんです。", wrong: ["頭が痛いなんです。", "頭が痛いだんです。"] },
        { fr: "C'est que demain, c'est mon jour de congé.", answer: "明日は休みなんです。", wrong: ["明日は休みんです。", "明日は休みだんです。"] },
        { fr: "Pourquoi n'es-tu pas venu·e ?", answer: "どうして来なかったんですか。", wrong: ["どうして来なかったなんですか。", "どうして来ないだったんですか。"] },
        { fr: "Tu as mangé ? (familier)", answer: "ご飯、食べた？", wrong: ["ご飯、食べただ？", "ご飯、食べたです？"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Il fait chaud (familier).", answers: ["暑い。", "あつい。"] },
        { fr: "Je n'étais pas libre (familier).", answers: ["暇じゃなかった。", "ひまじゃなかった。"] },
        { fr: "Tu viens ? (familier)", answers: ["来る？", "くる？", "来るの？", "くるの？"] },
        { fr: "C'est que j'ai mal à la tête.", answers: ["頭が痛いんです。", "あたまがいたいんです。"] },
        { fr: "C'est que c'est mon jour de congé.", answers: ["休みなんです。", "やすみなんです。"] },
        { fr: "Mon grand frère est étudiant (familier).", answers: ["兄は学生だ。", "あにはがくせいだ。"] },
      ],
    },
    morePractice: { href: "/conjugaison", label: "S'entraîner aux formes familières" },
  },
  {
    id: "n4-experiences",
    title: "Expériences et conseils : ～たことがある, ～ながら, ～たほうがいい",
    minutes: 15,
    summary: "Dire ce qu'on a déjà fait (ou jamais fait), faire deux choses à la fois, et donner un conseil.",
    sections: [
      {
        title: "« J'ai déjà… » : ～たことがあります",
        formula: "Verbe en た + [ことがあります]　／　jamais : + [ことがありません]",
        paragraphs: [
          "Pour parler d'une **expérience**, on prend la forme en た du verbe (行く → 行った, 食べる → 食べた, 見る → 見た), puis on ajoute [ことがあります].",
          "Au négatif, [ことがありません] veut dire « je n'ai jamais… ». Avec か à la fin, c'est la question « as-tu déjà… ? ».",
        ],
        examples: [
          { ja: "富士山に登った[ことがあります]。", reading: "ふじさんにのぼった[ことがあります]。", romaji: "Fujisan ni nobotta [koto ga arimasu].", fr: "J'ai déjà gravi le mont Fuji." },
          { ja: "寿司を食べた[ことがありません]。", reading: "すしをたべた[ことがありません]。", romaji: "Sushi o tabeta [koto ga arimasen].", fr: "Je n'ai jamais mangé de sushis." },
          { ja: "日本に行った[ことがありますか]。", reading: "にほんにいった[ことがありますか]。", romaji: "Nihon ni itta [koto ga arimasu ka].", fr: "Es-tu déjà allé·e au Japon ?" },
        ],
        tip: "Toujours la forme en た : 行く[ことがあります] veut dire « il m'arrive d'aller », pas « je suis déjà allé·e ».",
      },
      {
        title: "Deux actions en même temps : ～ながら",
        formula: "Verbe en ます sans ます + [ながら] + action principale",
        paragraphs: [
          "Forme en ます sans ます, puis [ながら] : 聞きます → 聞き[ながら]. L'action secondaire vient avec ながら, l'action **principale** se place à la fin de la phrase.",
        ],
        examples: [
          { ja: "音楽を聞き[ながら]勉強します。", reading: "おんがくをきき[ながら]べんきょうします。", romaji: "Ongaku o kiki[nagara] benkyou shimasu.", fr: "J'étudie en écoutant de la musique." },
          { ja: "歩き[ながら]話しましょう。", reading: "あるき[ながら]はなしましょう。", romaji: "Aruki[nagara] hanashimashou.", fr: "Parlons en marchant." },
        ],
        tip: "Les deux actions sont faites par **la même personne**, et c'est la dernière qui compte le plus.",
      },
      {
        title: "Donner un conseil : ～たほうがいい",
        formula: "Verbe en た + [ほうがいいです]　／　verbe en ない + [ほうがいいです]",
        paragraphs: [
          "Pour conseiller : forme en た + [ほうがいいです] (« tu ferais mieux de… »). Pour déconseiller : forme en ない + [ほうがいいです].",
          "C'est un conseil assez direct : avec un supérieur, on l'adoucit avec と思います.",
        ],
        examples: [
          { ja: "早く寝た[ほうがいいです]よ。", reading: "はやくねた[ほうがいいです]よ。", romaji: "Hayaku neta [hou ga ii desu] yo.", fr: "Tu ferais mieux de te coucher tôt." },
          { ja: "海で泳がない[ほうがいいです]。", reading: "うみでおよがない[ほうがいいです]。", romaji: "Umi de oyoganai [hou ga ii desu].", fr: "Il vaut mieux ne pas nager dans la mer." },
          { ja: "京都の旅館に泊まった[ほうがいい]と思います。", reading: "きょうとのりょかんにとまった[ほうがいい]とおもいます。", romaji: "Kyouto no ryokan ni tomatta [hou ga ii] to omoimasu.", fr: "Je pense que tu devrais dormir dans un ryokan à Kyoto." },
        ],
        tip: "Le conseil prend la forme en た même s'il parle du futur : 行った[ほうがいい].",
      },
    ],
    vocabulary: [
      { ja: "旅館", reading: "りょかん", fr: "auberge japonaise" },
      { ja: "神社", reading: "じんじゃ", fr: "sanctuaire shinto" },
      { ja: "漫画", reading: "まんが", fr: "manga" },
      { ja: "試合", reading: "しあい", fr: "match" },
      { ja: "趣味", reading: "しゅみ", fr: "passe-temps" },
      { ja: "泊まる", reading: "とまる", fr: "loger, dormir (à l'hôtel)" },
      { ja: "世界", reading: "せかい", fr: "monde" },
      { ja: "海", reading: "うみ", fr: "mer" },
    ],
    kanji: ["旅", "館", "世", "界", "海", "洋", "京", "映", "画"],
    keyPoints: [
      "Expérience : forme en た + [ことがあります] ; jamais : [ことがありません].",
      "En même temps : ます sans ます + [ながら], l'action principale à la fin.",
      "Conseil : forme en た + [ほうがいい] ; déconseiller : forme en ない + [ほうがいい].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "J'ai déjà vu ce film.", answer: "この映画を見たことがあります。", wrong: ["この映画を見たことがありません。", "この映画を見ることがあります。"] },
        { fr: "Je n'ai jamais dormi dans un ryokan.", answer: "旅館に泊まったことがありません。", wrong: ["旅館に泊まったことがあります。", "旅館に泊まることがありません。"] },
        { fr: "As-tu déjà lu ce manga ?", answer: "この漫画を読んだことがありますか。", wrong: ["この漫画を読んだことがあります。", "この漫画を読むことがありますか。"] },
        { fr: "J'étudie en écoutant de la musique.", answer: "音楽を聞きながら勉強します。", wrong: ["勉強しながら音楽を聞きます。", "音楽を聞いたことがあります。"] },
        { fr: "Je mange en regardant la télévision.", answer: "テレビを見ながら食べます。", wrong: ["食べながらテレビを見ます。", "テレビを見たことがあります。"] },
        { fr: "Je suis déjà allé·e dans un sanctuaire à Kyoto.", answer: "京都の神社に行ったことがあります。", wrong: ["京都の神社に行くことがあります。", "京都の神社に行ったことがありません。"] },
        { fr: "Parlons en marchant.", answer: "歩きながら話しましょう。", wrong: ["歩いたことがあります。", "歩きながら話しました。"] },
        { fr: "Je n'ai jamais vu de match de judo.", answer: "柔道の試合を見たことがありません。", wrong: ["柔道の試合を見たことがあります。", "柔道の試合を見ることがありません。"] },
        { fr: "Tu ferais mieux de prendre un médicament.", answer: "薬を飲んだほうがいいです。", wrong: ["薬を飲みながらいいです。", "薬を飲んだことがいいです。"] },
        { fr: "Il vaut mieux ne pas sortir ce soir.", answer: "今晩は出かけないほうがいいです。", wrong: ["今晩は出かけなかったほうがいいです。", "今晩は出かけないことがあります。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Je suis déjà allé·e au Japon.", answers: ["日本に行ったことがあります。", "にほんにいったことがあります。"] },
        { fr: "Je n'ai jamais mangé de sushis.", answers: ["寿司を食べたことがありません。", "すしをたべたことがありません。", "すしを食べたことがありません。"] },
        { fr: "As-tu déjà vu ce film ?", answers: ["この映画を見たことがありますか。", "このえいがをみたことがありますか。"] },
        { fr: "J'étudie en écoutant de la musique.", answers: ["音楽を聞きながら勉強します。", "おんがくをききながらべんきょうします。"] },
        { fr: "Tu ferais mieux de te coucher tôt.", answers: ["早く寝たほうがいいです。", "はやくねたほうがいいです。", "早く寝たほうがいいですよ。", "はやくねたほうがいいですよ。"] },
        { fr: "Parlons en marchant.", answers: ["歩きながら話しましょう。", "あるきながらはなしましょう。"] },
      ],
    },
    morePractice: { href: "/exercices/grammaire?point=n4-koto-ga-aru", label: "Plus de phrases avec ～たことがある" },
  },
  {
    id: "n4-avis",
    title: "Donner son avis : ～と思う, ～そう, ～と言う",
    minutes: 15,
    summary: "Dire ce qu'on pense, décrire ce qui a l'air d'être (« ça a l'air bon »), et rapporter ce que quelqu'un a dit.",
    sections: [
      {
        title: "« Je pense que… » : ～と思います",
        formula: "Forme familière + [と思います]　／　nom ou な + [だと思います]",
        paragraphs: [
          "On met la phrase à la forme familière, puis [と思います] : 降る → 降る[と思います]. Au négatif : 来ない[と思います].",
          "Avec un nom ou un adjectif en な, on ajoute だ avant と : 静か[だと思います]. Avec un adjectif en い, jamais de だ : 難しい[と思います].",
        ],
        examples: [
          { ja: "明日は雨が降る[と思います]。", reading: "あしたはあめがふる[とおもいます]。", romaji: "Ashita wa ame ga furu [to omoimasu].", fr: "Je pense qu'il va pleuvoir demain." },
          { ja: "彼は来ない[と思います]。", reading: "かれはこない[とおもいます]。", romaji: "Kare wa konai [to omoimasu].", fr: "Je pense qu'il ne viendra pas." },
          { ja: "日本語は難しい[と思います]。", reading: "にほんごはむずかしい[とおもいます]。", romaji: "Nihongo wa muzukashii [to omoimasu].", fr: "Je trouve que le japonais est difficile." },
        ],
        tip: "と思います parle de **ton** avis. Pour l'avis d'un autre : 彼は…[と思っています] (il pense que…).",
      },
      {
        title: "« Ça a l'air… » : ～そうです",
        formula: "おいし[そう]　静か[そう]　降り[そう]　／　いい → [よさそう]",
        paragraphs: [
          "Pour dire ce qu'on **voit** (l'apparence) : adjectif en い sans い + [そう] (おいしい → おいし[そう]), adjectif en な + [そう] (静か[そう]), verbe en ます sans ます + [そう] (降り[そう]).",
          "Exception : いい devient [よさそう].",
        ],
        examples: [
          { ja: "このケーキはおいし[そう]です。", reading: "このケーキはおいし[そう]です。", romaji: "Kono keeki wa oishi[sou] desu.", fr: "Ce gâteau a l'air bon." },
          { ja: "今にも雨が降り[そう]です。", reading: "いまにもあめがふり[そう]です。", romaji: "Ima ni mo ame ga furi[sou] desu.", fr: "On dirait qu'il va pleuvoir d'un instant à l'autre." },
          { ja: "彼女は嬉し[そう]です。", reading: "かのじょはうれし[そう]です。", romaji: "Kanojo wa ureshi[sou] desu.", fr: "Elle a l'air contente." },
        ],
        tip: "おいしいそうです (avec い) veut dire « on dit que c'est bon » : c'est le ouï-dire, une autre forme.",
      },
      {
        title: "Rapporter des paroles : ～と言う",
        formula: "「paroles」[と言いました]　／　forme familière + [と言っていました]",
        paragraphs: [
          "Pour citer exactement : 「…」[と言いました]. Pour rapporter le sens : forme familière + [と言っていました] (« il a dit que… »).",
          "Pour demander comment on dit quelque chose : これは日本語で何[と言いますか].",
        ],
        examples: [
          { ja: "先生は「明日は休みです」[と言いました]。", reading: "せんせいは「あしたはやすみです」[といいました]。", romaji: "Sensei wa « ashita wa yasumi desu » [to iimashita].", fr: "Le professeur a dit : « Demain, c'est congé. »" },
          { ja: "田中さんは来ない[と言っていました]。", reading: "たなかさんはこない[といっていました]。", romaji: "Tanaka-san wa konai [to itte imashita].", fr: "Monsieur Tanaka a dit qu'il ne viendrait pas." },
          { ja: "これは日本語で何[と言いますか]。", reading: "これはにほんごでなん[といいますか]。", romaji: "Kore wa nihongo de nan [to iimasu ka].", fr: "Comment dit-on ça en japonais ?" },
        ],
      },
    ],
    vocabulary: [
      { ja: "彼", reading: "かれ", fr: "il, lui" },
      { ja: "彼女", reading: "かのじょ", fr: "elle, petite amie" },
      { ja: "嬉しい", reading: "うれしい", fr: "content" },
      { ja: "悲しい", reading: "かなしい", fr: "triste" },
      { ja: "優しい", reading: "やさしい", fr: "gentil" },
      { ja: "意味", reading: "いみ", fr: "sens, signification" },
      { ja: "考える", reading: "かんがえる", fr: "réfléchir, penser" },
      { ja: "同じ", reading: "おなじ", fr: "pareil, même" },
    ],
    kanji: ["思", "考", "言", "意", "味", "心", "同"],
    keyPoints: [
      "Avis : forme familière + [と思います] (静か[だと思います], 難しい[と思います]).",
      "Apparence : adjectif sans い, ou verbe sans ます, + [そう] ; いい → [よさそう].",
      "Paroles rapportées : 「…」[と言いました] ; forme familière + [と言っていました].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Je pense qu'il va neiger demain.", answer: "明日は雪が降ると思います。", wrong: ["明日は雪が降りそうと思います。", "明日は雪が降るだと思います。"] },
        { fr: "Elle a l'air triste.", answer: "彼女は悲しそうです。", wrong: ["彼女は悲しいと思います。", "彼女は悲しいそうです。"] },
        { fr: "Ce professeur a l'air gentil.", answer: "あの先生は優しそうです。", wrong: ["あの先生は優しいそうです。", "あの先生は優しかったです。"] },
        { fr: "Je pense que ce film est intéressant.", answer: "この映画はおもしろいと思います。", wrong: ["この映画はおもしろそうです。", "この映画はおもしろいだと思います。"] },
        { fr: "Je pense que cette ville est calme.", answer: "この町は静かだと思います。", wrong: ["この町は静かと思います。", "この町は静かそうです。"] },
        { fr: "Il a l'air content.", answer: "彼は嬉しそうです。", wrong: ["彼は嬉しいと思います。", "彼は嬉しくそうです。"] },
        { fr: "Ce ramen a l'air bon.", answer: "このラーメンはおいしそうです。", wrong: ["このラーメンはおいしいそうです。", "このラーメンはおいしかったと思います。"] },
        { fr: "Ça a l'air bien.", answer: "よさそうです。", wrong: ["いいそうです。", "いさそうです。"] },
        { fr: "Le professeur a dit qu'il n'y avait pas cours demain.", answer: "先生は明日授業がないと言っていました。", wrong: ["先生は明日授業がないそうと言っていました。", "先生は明日授業がないだと言っていました。"] },
        { fr: "Comment dit-on ça en japonais ?", answer: "これは日本語で何と言いますか。", wrong: ["これは日本語で何を言いますか。", "これは日本語で何と思いますか。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Je pense qu'il va pleuvoir.", answers: ["雨が降ると思います。", "あめがふるとおもいます。"] },
        { fr: "Ça a l'air bon !", answers: ["おいしそうです。", "おいしそう。", "おいしそうですね。"] },
        { fr: "Je pense que c'est difficile.", answers: ["難しいと思います。", "むずかしいとおもいます。"] },
        { fr: "Elle a l'air contente.", answers: ["彼女は嬉しそうです。", "かのじょはうれしそうです。"] },
        { fr: "Je pense qu'il ne viendra pas.", answers: ["彼は来ないと思います。", "かれはこないとおもいます。"] },
        { fr: "Comment dit-on ça en japonais ?", answers: ["これは日本語で何と言いますか。", "これはにほんごでなんといいますか。"] },
      ],
    },
    morePractice: { href: "/exercices/grammaire?point=n4-to-omou", label: "Plus de phrases avec ～と思う" },
  },
  {
    id: "n4-intentions",
    title: "Projets et intentions : forme volitive, つもり, 予定",
    minutes: 15,
    summary: "Proposer en style familier (行こう), dire ce qu'on compte faire, et ce qui est prévu.",
    sections: [
      {
        title: "La forme volitive : 行こう, 食べよう",
        formula: "Groupe 1 : son en u → [son en o + う]　Groupe 2 : る → [よう]　する → [しよう]　来る → [来よう]",
        paragraphs: [
          "La forme volitive est la version familière de ～ましょう : 行[こう] (allons-y !), 食べ[よう] (mangeons !).",
          "Groupe 1 : le dernier son passe en -o, puis う : 書く → 書[こう], 飲む → 飲[もう], 帰る → 帰[ろう]. Groupe 2 : る → [よう]. Irréguliers : する → [しよう], 来る → [来よう] (こよう).",
        ],
        examples: [
          { ja: "一緒に帰[ろう]。", reading: "いっしょにかえ[ろう]。", romaji: "Issho ni kae[rou].", fr: "Rentrons ensemble (familier)." },
          { ja: "そろそろ始め[よう]か。", reading: "そろそろはじめ[よう]か。", romaji: "Sorosoro hajime[you] ka.", fr: "On commence ? (familier)" },
        ],
        tip: "Groupe 1 : on garde la consonne, seule la voyelle change : 待つ → [待とう], 話す → [話そう].",
      },
      {
        title: "« Je pense faire… » : ～ようと思う",
        formula: "Forme volitive + [と思います] (décision)　／　+ [と思っています] (projet)",
        paragraphs: [
          "Forme volitive + [と思います] : une décision qu'on vient de prendre. Avec [と思っています] : un projet qu'on a depuis un moment.",
        ],
        examples: [
          { ja: "今年の夏、海に行[こうと思っています]。", reading: "ことしのなつ、うみにい[こうとおもっています]。", romaji: "Kotoshi no natsu, umi ni i[kou to omotte imasu].", fr: "Cet été, je compte aller à la mer." },
          { ja: "明日は早く起き[ようと思います]。", reading: "あしたははやくおき[ようとおもいます]。", romaji: "Ashita wa hayaku oki[you to omoimasu].", fr: "Demain, je pense me lever tôt." },
        ],
      },
      {
        title: "Intention ferme ou programme : つもり et 予定",
        formula: "Dictionnaire + [つもりです]　（ない + [つもりです]）　／　dictionnaire ou nom の + [予定です]",
        paragraphs: [
          "[つもり] : une **intention ferme** : 来年、日本に留学する[つもりです]. Au négatif : 行かない[つもりです] (je n'ai pas l'intention d'y aller).",
          "[予定] : ce qui est **prévu**, souvent par un planning : 三時に着く[予定です], 会議は来週[の予定です].",
        ],
        examples: [
          { ja: "春から日本語学校に通う[つもりです]。", reading: "はるからにほんごがっこうにかよう[つもりです]。", romaji: "Haru kara nihongo gakkou ni kayou [tsumori desu].", fr: "À partir du printemps, je compte suivre une école de japonais." },
          { ja: "電車は十時に着く[予定です]。", reading: "でんしゃはじゅうじにつく[よていです]。", romaji: "Densha wa juuji ni tsuku [yotei desu].", fr: "Le train doit arriver à 10 heures." },
          { ja: "今度の冬はスキーをしない[つもりです]。", reading: "こんどのふゆはスキーをしない[つもりです]。", romaji: "Kondo no fuyu wa sukii o shinai [tsumori desu].", fr: "Cet hiver, je n'ai pas l'intention de skier." },
        ],
        tip: "On évite つもり pour questionner un supérieur : 先生も行くつもりですか sonne trop direct.",
      },
    ],
    vocabulary: [
      { ja: "予定", reading: "よてい", fr: "programme, ce qui est prévu" },
      { ja: "計画", reading: "けいかく", fr: "projet, plan" },
      { ja: "今度", reading: "こんど", fr: "la prochaine fois, cette fois-ci" },
      { ja: "春", reading: "はる", fr: "printemps" },
      { ja: "秋", reading: "あき", fr: "automne" },
      { ja: "留学", reading: "りゅうがく", fr: "études à l'étranger" },
      { ja: "通う", reading: "かよう", fr: "aller régulièrement, fréquenter" },
      { ja: "来週", reading: "らいしゅう", fr: "la semaine prochaine" },
    ],
    kanji: ["春", "夏", "秋", "冬", "計", "度", "週", "早"],
    keyPoints: [
      "Volitive : 書く → [書こう], 食べる → [食べよう], [しよう], [来よう].",
      "Je compte faire : forme volitive + [と思っています].",
      "Intention ferme : [つもりです] ; c'est prévu : [予定です].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Allons-y ! (familier)", answer: "行こう。", wrong: ["行きよう。", "行くよう。"] },
        { fr: "Mangeons ! (familier)", answer: "食べよう。", wrong: ["食べこう。", "食べろう。"] },
        { fr: "On rentre ? (familier)", answer: "帰ろうか。", wrong: ["帰りようか。", "帰るようか。"] },
        { fr: "Attendons encore un peu (familier).", answer: "もう少し待とう。", wrong: ["もう少し待つよう。", "もう少し待よう。"] },
        { fr: "Cet été, je compte aller à la mer.", answer: "今年の夏、海に行こうと思っています。", wrong: ["今年の夏、海に行きようと思っています。", "今年の夏、海に行こうつもりです。"] },
        { fr: "J'ai l'intention d'étudier au Japon l'année prochaine.", answer: "来年、日本に留学するつもりです。", wrong: ["来年、日本に留学したつもりです。", "来年、日本に留学しようつもりです。"] },
        { fr: "Je n'ai pas l'intention de l'acheter.", answer: "買わないつもりです。", wrong: ["買わなかったつもりです。", "買おうないつもりです。"] },
        { fr: "Le train doit arriver à 10 heures.", answer: "電車は十時に着く予定です。", wrong: ["電車は十時に着こう予定です。", "電車は十時に着いた予定です。"] },
        { fr: "La réunion est prévue pour la semaine prochaine.", answer: "会議は来週の予定です。", wrong: ["会議は来週な予定です。", "会議は来週だ予定です。"] },
        { fr: "Demain, je pense me lever tôt.", answer: "明日は早く起きようと思います。", wrong: ["明日は早く起きろうと思います。", "明日は早く起こうと思います。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Allons-y ! (familier)", answers: ["行こう。", "いこう。"] },
        { fr: "Mangeons ! (familier)", answers: ["食べよう。", "たべよう。"] },
        { fr: "Je compte aller au Japon.", answers: ["日本に行くつもりです。", "にほんにいくつもりです。", "日本へ行くつもりです。", "にほんへいくつもりです。"] },
        { fr: "Je pense rentrer tôt.", answers: ["早く帰ろうと思います。", "はやくかえろうとおもいます。"] },
        { fr: "Le train doit arriver à 10 heures.", answers: ["電車は十時に着く予定です。", "でんしゃはじゅうじにつくよていです。"] },
        { fr: "Je n'ai pas l'intention d'y aller.", answers: ["行かないつもりです。", "いかないつもりです。"] },
      ],
    },
  },
];
