import type { Lesson } from "@/lib/course/lessons";

// Leçons du cours N5 qui complètent le programme (nombres, heure, こそあど,
// particules, adjectifs, formes simples, avant/après, envies, compteurs).
// Même format que n5-lessons.ts ; le numéro est donné par l'ordre du cours.
export const N5_EXTRA_LESSONS: Omit<Lesson, "number">[] = [
  {
    id: "n5-nombres",
    title: "Les nombres, les prix et l'argent",
    minutes: 15,
    summary: "Compter jusqu'à 99 999, dire un prix en yens et demander « combien ? ».",
    sections: [
      {
        title: "De 1 à 99 : on assemble",
        formula: "[十] + chiffre = 11 à 19　／　chiffre + [十] = 20, 30…",
        paragraphs: [
          "Les dix premiers : 一 (いち), 二 (に), 三 (さん), 四 (よん / し), 五 (ご), 六 (ろく), 七 (なな / しち), 八 (はち), 九 (きゅう / く), 十 (じゅう).",
          "Ensuite, on **assemble** comme des briques : 十一 = 10 + 1, 二十 = 2 × 10, 三十五 = 3 × 10 + 5. Pas de mot spécial comme « onze » ou « vingt ».",
        ],
        examples: [
          { ja: "[十]一", reading: "[じゅう]いち", romaji: "[juu]ichi", fr: "11" },
          { ja: "二[十]", reading: "に[じゅう]", romaji: "ni[juu]", fr: "20" },
          { ja: "四[十]五", reading: "よん[じゅう]ご", romaji: "yon[juu]go", fr: "45" },
          { ja: "九[十]九", reading: "きゅう[じゅう]きゅう", romaji: "kyuu[juu]kyuu", fr: "99" },
        ],
        tip: "4, 7 et 9 ont deux lectures. Pour compter, on préfère [よん], [なな] et [きゅう] : し rappelle le mot « mort » (死).",
      },
      {
        title: "Cent, mille, dix mille",
        formula: "[百] = 100　[千] = 1 000　[万] = 10 000",
        paragraphs: [
          "Même principe : 三百 = 300, 五千 = 5 000. Attention aux **sons qui changent** : 三百 (さん[びゃく]), 六百 (ろっ[ぴゃく]), 八百 (はっ[ぴゃく]), 三千 (さん[ぜん]).",
          "Le japonais compte par paquets de **dix mille** : [万] (まん). 10 000 = 一万, 50 000 = 五万, 100 000 = 十万 (« dix fois dix mille »).",
        ],
        examples: [
          { ja: "三[百]", reading: "さん[びゃく]", romaji: "san[byaku]", fr: "300" },
          { ja: "三[千]", reading: "さん[ぜん]", romaji: "san[zen]", fr: "3 000" },
          { ja: "一[万]", reading: "いち[まん]", romaji: "ichi[man]", fr: "10 000" },
          { ja: "十[万]", reading: "じゅう[まん]", romaji: "juu[man]", fr: "100 000" },
        ],
        tip: "On ne dit pas 一百 ni 一千 : 100 = [百], 1 000 = [千]. Mais 10 000 = [一万], avec le 一.",
      },
      {
        title: "Les prix : 円 et いくら",
        formula: "Nombre + [円]　／　これは[いくらですか]",
        paragraphs: [
          "La monnaie japonaise est le **yen** : [円] (えん). 500円 = 500 yens. Pour demander un prix : これは[いくらですか].",
          "Au magasin, on montre l'objet et on dit : これを[ください] (je prends ça).",
        ],
        examples: [
          { ja: "このかばんは[いくらですか]。", reading: "このかばんは[いくらですか]。", romaji: "Kono kaban wa [ikura desu ka].", fr: "Combien coûte ce sac ?" },
          { ja: "三千五百[円]です。", reading: "さんぜんごひゃく[えん]です。", romaji: "Sanzen gohyaku [en] desu.", fr: "C'est 3 500 yens." },
          { ja: "これを[ください]。", reading: "これを[ください]。", romaji: "Kore o [kudasai].", fr: "Je prends ça, s'il vous plaît." },
        ],
        tip: "On écrit 円 mais on dit [えん] : jamais « yen » en japonais. Et [いくら] (combien d'argent) n'est pas [いくつ] (combien d'objets).",
      },
    ],
    vocabulary: [
      { ja: "百", reading: "ひゃく", fr: "cent" },
      { ja: "千", reading: "せん", fr: "mille" },
      { ja: "万", reading: "まん", fr: "dix mille" },
      { ja: "お金", reading: "おかね", fr: "argent" },
      { ja: "いくら", reading: "いくら", fr: "combien (prix)" },
      { ja: "店", reading: "みせ", fr: "magasin" },
    ],
    kanji: ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "百", "千", "万", "円"],
    keyPoints: [
      "On assemble : [二十五] = 2 × 10 + 5.",
      "Par paquets de dix mille : [一万] = 10 000, [十万] = 100 000.",
      "Prix : nombre + [円] ; « combien ? » : [いくらですか].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Combien coûte ce livre ?", answer: "この本はいくらですか。", wrong: ["この本は何ですか。", "この本はどこですか。"] },
        { fr: "C'est 800 yens.", answer: "八百円です。", wrong: ["八十円です。", "八千円です。"] },
        { fr: "C'est 3 000 yens.", answer: "三千円です。", wrong: ["三百円です。", "三万円です。"] },
        { fr: "C'est 10 000 yens.", answer: "一万円です。", wrong: ["十千円です。", "一千円です。"] },
        { fr: "C'est 1 500 yens.", answer: "千五百円です。", wrong: ["五千百円です。", "百五十円です。"] },
        { fr: "Ce café coûte 450 yens.", answer: "このコーヒーは四百五十円です。", wrong: ["このコーヒーは四千五十円です。", "このコーヒーは四十五円です。"] },
        { fr: "C'est 60 000 yens.", answer: "六万円です。", wrong: ["六千円です。", "六十万円です。"] },
        { fr: "Je prends ça, s'il vous plaît.", answer: "これをください。", wrong: ["これはください。", "これをいくらですか。"] },
        { fr: "Combien coûte ce sac ?", answer: "このかばんはいくらですか。", wrong: ["このかばんはいくつですか。", "このかばんはだれですか。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Combien ça coûte ?", answers: ["これはいくらですか。", "いくらですか。"] },
        { fr: "C'est 500 yens.", answers: ["五百円です。", "ごひゃくえんです。", "500円です。", "500えんです。"] },
        { fr: "Un café, s'il vous plaît.", answers: ["コーヒーをください。", "コーヒーください。"] },
        { fr: "C'est 10 000 yens.", answers: ["一万円です。", "いちまんえんです。"] },
        { fr: "C'est 3 000 yens.", answers: ["三千円です。", "さんぜんえんです。"] },
        { fr: "Combien coûte ce sac ?", answers: ["このかばんはいくらですか。"] },
      ],
    },
  },
  {
    id: "n5-heure-dates",
    title: "L'heure, les jours et les dates",
    minutes: 15,
    summary: "Lire l'heure, nommer les jours de la semaine et les mois, et placer une action dans le temps.",
    sections: [
      {
        title: "Quelle heure est-il ?",
        formula: "Nombre + [時] (heure)　／　[半] = et demie　／　[午前] matin, [午後] après-midi",
        paragraphs: [
          "L'heure : nombre + [時] (じ). 3時 = 3 heures. Les minutes : nombre + 分 (ふん ou ぷん : 五分 ごふん, 十分 じゅっぷん). « Et demie » : [半] (はん).",
          "Le matin et l'après-midi se disent [午前] (ごぜん) et [午後] (ごご), placés **avant** l'heure : 午後三時 = 15 heures. Pour demander : 今、[何時]ですか.",
        ],
        examples: [
          { ja: "今、[何時]ですか。", reading: "いま、[なんじ]ですか。", romaji: "Ima, [nanji] desu ka.", fr: "Quelle heure est-il ?" },
          { ja: "[午後]三[時半]です。", reading: "[ごご]さん[じはん]です。", romaji: "[Gogo] san[ji han] desu.", fr: "Il est 15 h 30." },
          { ja: "七[時]に起きます。", reading: "しち[じ]におきます。", romaji: "Shichi[ji] ni okimasu.", fr: "Je me lève à 7 heures." },
        ],
        tip: "4 h, 7 h et 9 h se disent [よじ], [しちじ] et [くじ] : pas よんじ ni きゅうじ.",
      },
      {
        title: "Les jours de la semaine",
        formula: "[月]曜日 lundi　[火] mardi　[水] mercredi　[木] jeudi　[金] vendredi　[土] samedi　[日] dimanche",
        paragraphs: [
          "Chaque jour porte le nom d'un astre ou d'un élément : la **lune** (月), le **feu** (火), l'**eau** (水), le **bois** (木), le **métal** (金), la **terre** (土) et le **soleil** (日), suivi de 曜日 (ようび).",
          "Pour une action à un jour ou une heure précise, on ajoute [に] : 月曜日[に]. Mais pas après 今日, 明日 ou [毎日] (tous les jours).",
        ],
        examples: [
          { ja: "[金曜日]に映画を見ます。", reading: "[きんようび]にえいがをみます。", romaji: "[Kin'youbi] ni eiga o mimasu.", fr: "Je regarde un film vendredi." },
          { ja: "[毎日]日本語を勉強します。", reading: "[まいにち]にほんごをべんきょうします。", romaji: "[Mainichi] nihongo o benkyou shimasu.", fr: "J'étudie le japonais tous les jours." },
          { ja: "今日は[何曜日]ですか。", reading: "きょうは[なんようび]ですか。", romaji: "Kyou wa [nan'youbi] desu ka.", fr: "Quel jour sommes-nous ?" },
        ],
        tip: "Pas de に après 今日, 明日 ni [毎日] : 毎日に勉強します est faux.",
      },
      {
        title: "Les mois et les années",
        formula: "Nombre + [月] (mois)　／　Nombre + [年] (année)",
        paragraphs: [
          "Les mois sont simplement numérotés : [一月] (janvier), [二月] (février)… jusqu'à [十二月]. Attention : 四月 se lit しがつ, 七月 しちがつ, 九月 くがつ.",
          "L'année : nombre + [年] (ねん). 2026年 = l'année 2026. Les dates vont du plus grand au plus petit : **année, mois, jour**.",
        ],
        examples: [
          { ja: "誕生日は[三月]です。", reading: "たんじょうびは[さんがつ]です。", romaji: "Tanjoubi wa [sangatsu] desu.", fr: "Mon anniversaire est en mars." },
          { ja: "[来年]、日本に行きます。", reading: "[らいねん]、にほんにいきます。", romaji: "[Rainen], Nihon ni ikimasu.", fr: "J'irai au Japon l'année prochaine." },
        ],
        tip: "Ne confonds pas [一月] (いちがつ, janvier) et 一か月 (いっかげつ, une durée d'un mois).",
      },
    ],
    vocabulary: [
      { ja: "午前", reading: "ごぜん", fr: "le matin (avant midi)" },
      { ja: "午後", reading: "ごご", fr: "l'après-midi" },
      { ja: "半", reading: "はん", fr: "et demie, moitié" },
      { ja: "毎日", reading: "まいにち", fr: "tous les jours" },
      { ja: "今日", reading: "きょう", fr: "aujourd'hui" },
      { ja: "明日", reading: "あした", fr: "demain" },
      { ja: "来年", reading: "らいねん", fr: "l'année prochaine" },
      { ja: "誕生日", reading: "たんじょうび", fr: "anniversaire" },
    ],
    kanji: ["時", "半", "午", "年", "月", "日", "火", "水", "金", "土", "毎"],
    keyPoints: [
      "Heure : nombre + [時] ; « et demie » : [半] ; [午前] / [午後] devant l'heure.",
      "Jours : [月・火・水・木・金・土・日] + 曜日.",
      "Moment précis + [に], sauf après 今日, 明日 et 毎日.",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Il est 9 heures.", answer: "今、九時です。", wrong: ["今、九分です。", "今、九月です。"] },
        { fr: "Il est 15 h 30.", answer: "午後三時半です。", wrong: ["午前三時半です。", "午後三時です。"] },
        { fr: "Je me lève à 7 heures.", answer: "七時に起きます。", wrong: ["七時で起きます。", "七時を起きます。"] },
        { fr: "J'étudie tous les jours.", answer: "毎日勉強します。", wrong: ["毎日に勉強します。", "毎日を勉強します。"] },
        { fr: "Quel jour sommes-nous ?", answer: "今日は何曜日ですか。", wrong: ["今日は何時ですか。", "今日は何月ですか。"] },
        { fr: "Je vais à la piscine le mardi.", answer: "火曜日にプールに行きます。", wrong: ["水曜日にプールに行きます。", "火曜日でプールに行きます。"] },
        { fr: "Mon anniversaire est en avril.", answer: "誕生日は四月です。", wrong: ["誕生日は四日です。", "誕生日は四年です。"] },
        { fr: "J'irai au Japon l'année prochaine.", answer: "来年、日本に行きます。", wrong: ["来月、日本に行きます。", "来年、日本に行きました。"] },
        { fr: "Je travaille le samedi matin.", answer: "土曜日の午前に働きます。", wrong: ["土曜日の午後に働きます。", "金曜日の午前に働きます。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Quelle heure est-il ?", answers: ["今、何時ですか。", "いま、なんじですか。", "何時ですか。", "なんじですか。"] },
        { fr: "Il est 10 heures.", answers: ["十時です。", "じゅうじです。"] },
        { fr: "C'est lundi.", answers: ["月曜日です。", "げつようびです。"] },
        { fr: "J'étudie tous les jours.", answers: ["毎日勉強します。", "まいにちべんきょうします。"] },
        { fr: "Il est 8 h 30.", answers: ["八時半です。", "はちじはんです。"] },
        { fr: "Mon anniversaire est en mai.", answers: ["誕生日は五月です。", "たんじょうびはごがつです。"] },
      ],
    },
  },
  {
    id: "n5-questions",
    title: "Ceci, cela et les questions : こそあど, 何, だれ, どこ",
    minutes: 15,
    summary: "Montrer ce qui est près ou loin, poser toutes les questions, et dire « quelque chose » ou « rien ».",
    sections: [
      {
        title: "これ, それ, あれ, どれ",
        formula: "[こ] près de moi　[そ] près de toi　[あ] loin des deux　[ど] question",
        paragraphs: [
          "Le japonais range les choses selon la **distance** : [これ] (ceci, près de moi), [それ] (cela, près de toi), [あれ] (cela, là-bas), [どれ] (lequel ?).",
          "Devant un nom, on utilise [この], [その], [あの], [どの] : この本 (ce livre-ci). Pour les lieux : [ここ], [そこ], [あそこ], [どこ].",
        ],
        examples: [
          { ja: "[これ]は何ですか。", reading: "[これ]はなんですか。", romaji: "[Kore] wa nan desu ka.", fr: "Qu'est-ce que c'est ?" },
          { ja: "[その]かばんは私のです。", reading: "[その]かばんはわたしのです。", romaji: "[Sono] kaban wa watashi no desu.", fr: "Ce sac (près de toi) est à moi." },
          { ja: "トイレは[あそこ]です。", reading: "トイレは[あそこ]です。", romaji: "Toire wa [asoko] desu.", fr: "Les toilettes sont là-bas." },
        ],
        tip: "これ ne se met jamais devant un nom : [この]本, pas これ本.",
      },
      {
        title: "Les mots pour poser une question",
        formula: "[何] quoi　[だれ] qui　[どこ] où　[いつ] quand　[どうして] pourquoi　[どう] comment",
        paragraphs: [
          "Le mot interrogatif prend **la place** de la réponse, et la phrase finit par か. Pas d'inversion comme en français : 駅は[どこ]ですか (la gare est où ?).",
          "何 se lit [なん] devant で, だ, の ou un compteur (何ですか, 何時), et [なに] ailleurs (何を食べますか).",
        ],
        examples: [
          { ja: "[だれ]が来ましたか。", reading: "[だれ]がきましたか。", romaji: "[Dare] ga kimashita ka.", fr: "Qui est venu ?" },
          { ja: "[いつ]日本に行きますか。", reading: "[いつ]にほんにいきますか。", romaji: "[Itsu] Nihon ni ikimasu ka.", fr: "Quand vas-tu au Japon ?" },
          { ja: "[何]を食べますか。", reading: "[なに]をたべますか。", romaji: "[Nani] o tabemasu ka.", fr: "Qu'est-ce que tu manges ?" },
          { ja: "[何語]を話しますか。", reading: "[なにご]をはなしますか。", romaji: "[Nanigo] o hanashimasu ka.", fr: "Quelle langue parles-tu ?" },
        ],
      },
      {
        title: "Quelque chose, rien : 何か et 何も",
        formula: "Interrogatif + [か] = quelque…　／　Interrogatif + [も] + verbe négatif = rien, personne",
        paragraphs: [
          "Avec [か], le mot devient « quelque » : 何か (quelque chose), だれか (quelqu'un), どこか (quelque part).",
          "Avec [も] et un verbe **négatif** : 何も…ません (rien), だれも…ません (personne), どこへも…ません (nulle part).",
        ],
        examples: [
          { ja: "何[か]飲みますか。", reading: "なに[か]のみますか。", romaji: "Nani [ka] nomimasu ka.", fr: "Tu bois quelque chose ?" },
          { ja: "何[も]食べませんでした。", reading: "なに[も]たべませんでした。", romaji: "Nani [mo] tabemasen deshita.", fr: "Je n'ai rien mangé." },
          { ja: "教室にだれ[も]いません。", reading: "きょうしつにだれ[も]いません。", romaji: "Kyoushitsu ni dare [mo] imasen.", fr: "Il n'y a personne dans la salle." },
        ],
        tip: "何も se lit [なにも] et demande un verbe **négatif** : 何も食べます est faux.",
      },
    ],
    vocabulary: [
      { ja: "何", reading: "なに", fr: "quoi" },
      { ja: "誰", reading: "だれ", fr: "qui" },
      { ja: "どこ", reading: "どこ", fr: "où" },
      { ja: "いつ", reading: "いつ", fr: "quand" },
      { ja: "国", reading: "くに", fr: "pays" },
      { ja: "外国", reading: "がいこく", fr: "pays étranger" },
      { ja: "外国人", reading: "がいこくじん", fr: "étranger (personne)" },
    ],
    kanji: ["何", "国", "語", "外"],
    keyPoints: [
      "[こ] ici, [そ] chez toi, [あ] là-bas, [ど] question ; devant un nom : [この / その / あの / どの].",
      "Le mot interrogatif prend la place de la réponse, et la phrase finit par か.",
      "何[か] = quelque chose ; 何[も] + négatif = rien.",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Qu'est-ce que c'est (près de toi) ?", answer: "それは何ですか。", wrong: ["それはだれですか。", "その何ですか。"] },
        { fr: "Ce livre-ci est intéressant.", answer: "この本はおもしろいです。", wrong: ["これ本はおもしろいです。", "あの本はおもしろいです。"] },
        { fr: "Où sont les toilettes ?", answer: "トイレはどこですか。", wrong: ["トイレはだれですか。", "トイレはいつですか。"] },
        { fr: "Qui est cette personne là-bas ?", answer: "あの人はだれですか。", wrong: ["あの人は何ですか。", "あの人はどこですか。"] },
        { fr: "Quand est ton anniversaire ?", answer: "誕生日はいつですか。", wrong: ["誕生日はどこですか。", "誕生日はいくらですか。"] },
        { fr: "Quelle langue parles-tu ?", answer: "何語を話しますか。", wrong: ["何語が話しますか。", "どこ語を話しますか。"] },
        { fr: "Tu bois quelque chose ?", answer: "何か飲みますか。", wrong: ["何も飲みますか。", "何を飲みませんか。"] },
        { fr: "Je n'ai rien acheté.", answer: "何も買いませんでした。", wrong: ["何か買いませんでした。", "何も買いました。"] },
        { fr: "Il n'y a personne.", answer: "だれもいません。", wrong: ["だれかいません。", "だれもいます。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Qu'est-ce que c'est ?", answers: ["これは何ですか。", "これはなんですか。", "何ですか。", "なんですか。"] },
        { fr: "Où est la gare ?", answers: ["駅はどこですか。", "えきはどこですか。"] },
        { fr: "Qui est-ce ?", answers: ["だれですか。"] },
        { fr: "Je n'ai rien mangé.", answers: ["何も食べませんでした。", "なにもたべませんでした。"] },
        { fr: "Quand viens-tu ?", answers: ["いつ来ますか。", "いつきますか。"] },
        { fr: "Ce livre est à moi.", answers: ["この本は私のです。", "このほんはわたしのです。"] },
      ],
    },
  },
  {
    id: "n5-particules",
    title: "Les particules en profondeur : は, が, も, と, や, の, から, まで",
    minutes: 18,
    summary: "Choisir entre は et が, dire « aussi », « avec », « de… à… », et finir une phrase avec ね ou よ.",
    sections: [
      {
        title: "は ou が ?",
        formula: "[は] : le thème (« quant à… »)　／　[が] : le sujet mis en avant, l'information nouvelle",
        paragraphs: [
          "[は] annonce **de quoi on parle** : 私[は]学生です (moi, je suis étudiant·e). [が] désigne **qui fait** ou **ce qui est**, surtout quand c'est l'information importante.",
          "Après un mot interrogatif, toujours [が] : だれ[が]来ましたか. Et la réponse garde が : 母[が]来ました.",
          "[が] s'emploie aussi avec 好き, 上手, わかる, ある et いる : 猫[が]好きです.",
        ],
        examples: [
          { ja: "私[は]フランス人です。", reading: "わたし[は]フランスじんです。", romaji: "Watashi [wa] furansujin desu.", fr: "Je suis français·e." },
          { ja: "だれ[が]来ましたか。", reading: "だれ[が]きましたか。", romaji: "Dare [ga] kimashita ka.", fr: "Qui est venu ?" },
          { ja: "母[が]来ました。", reading: "はは[が]きました。", romaji: "Haha [ga] kimashita.", fr: "C'est ma mère qui est venue." },
        ],
        tip: "Un mot interrogatif ne prend jamais は : だれは来ましたか est faux.",
      },
      {
        title: "Aussi, avec, et : も, と, や",
        formula: "A [も] (aussi)　／　A [と] B (A et B ; avec)　／　A [や] B (A, B, entre autres)",
        paragraphs: [
          "[も] remplace は ou が : 私[も]学生です (moi aussi). [と] relie des noms (« et ») ou veut dire « avec » : 友達[と]行きます.",
          "[や] donne **des exemples** sans tout citer : りんご[や]バナナ (des pommes, des bananes, etc.).",
        ],
        examples: [
          { ja: "父[も]母[も]元気です。", reading: "ちち[も]はは[も]げんきです。", romaji: "Chichi [mo] haha [mo] genki desu.", fr: "Mon père et ma mère vont bien tous les deux." },
          { ja: "友達[と]映画を見ました。", reading: "ともだち[と]えいがをみました。", romaji: "Tomodachi [to] eiga o mimashita.", fr: "J'ai vu un film avec un ami." },
          { ja: "パン[や]卵を買いました。", reading: "パン[や]たまごをかいました。", romaji: "Pan [ya] tamago o kaimashita.", fr: "J'ai acheté du pain, des œufs, etc." },
        ],
        tip: "と et や ne relient que des **noms**. Pour relier deux phrases, on utilise la forme en て.",
      },
      {
        title: "の, から, まで",
        formula: "A [の] B (le B de A)　／　[から] (depuis, de)　／　[まで] (jusqu'à)",
        paragraphs: [
          "[の] relie deux noms, le possesseur ou la précision **d'abord** : 私[の]本 (mon livre), 日本語[の]先生 (le professeur de japonais).",
          "[から] et [まで] marquent le début et la fin, dans le temps comme dans l'espace : 九時[から]五時[まで] (de 9 h à 17 h).",
        ],
        examples: [
          { ja: "これは父[の]車です。", reading: "これはちち[の]くるまです。", romaji: "Kore wa chichi [no] kuruma desu.", fr: "C'est la voiture de mon père." },
          { ja: "九時[から]五時[まで]働きます。", reading: "くじ[から]ごじ[まで]はたらきます。", romaji: "Kuji [kara] goji [made] hatarakimasu.", fr: "Je travaille de 9 h à 17 h." },
          { ja: "駅[から]家[まで]歩きます。", reading: "えき[から]いえ[まで]あるきます。", romaji: "Eki [kara] ie [made] arukimasu.", fr: "Je marche de la gare jusqu'à chez moi." },
        ],
        tip: "L'ordre de の est l'inverse du français : 父の車 = « père の voiture » = la voiture de mon père.",
      },
      {
        title: "En fin de phrase : か, ね, よ — et が (mais)",
        formula: "[か] question　[ね] n'est-ce pas ?　[よ] je t'apprends que…　／　phrase 1 + [が]、phrase 2 = mais",
        paragraphs: [
          "[ね] cherche l'**accord** de l'autre (« hein ? », « n'est-ce pas ? ») : いい天気です[ね]. [よ] donne une **information** que l'autre ne connaît pas : この店はおいしいです[よ].",
          "Après です ou ます, [が] relie deux phrases qui s'opposent : « mais ». 高いです[が]、おいしいです.",
        ],
        examples: [
          { ja: "今日は暑いです[ね]。", reading: "きょうはあついです[ね]。", romaji: "Kyou wa atsui desu [ne].", fr: "Il fait chaud aujourd'hui, hein ?" },
          { ja: "あの店は安いです[よ]。", reading: "あのみせはやすいです[よ]。", romaji: "Ano mise wa yasui desu [yo].", fr: "Ce magasin-là est bon marché, tu sais." },
          { ja: "日本語は難しいです[が]、おもしろいです。", reading: "にほんごはむずかしいです[が]、おもしろいです。", romaji: "Nihongo wa muzukashii desu [ga], omoshiroi desu.", fr: "Le japonais est difficile, mais intéressant." },
        ],
      },
    ],
    vocabulary: [
      { ja: "父", reading: "ちち", fr: "(mon) père" },
      { ja: "母", reading: "はは", fr: "(ma) mère" },
      { ja: "友達", reading: "ともだち", fr: "ami, amie" },
      { ja: "男", reading: "おとこ", fr: "homme" },
      { ja: "女", reading: "おんな", fr: "femme" },
      { ja: "子供", reading: "こども", fr: "enfant" },
      { ja: "卵", reading: "たまご", fr: "œuf" },
      { ja: "歩く", reading: "あるく", fr: "marcher" },
    ],
    kanji: ["父", "母", "友", "男", "女", "子"],
    keyPoints: [
      "[は] : le thème ; [が] : l'information nouvelle, toujours après だれ, 何, どこ.",
      "[も] aussi, [と] et / avec, [や] entre autres, [の] de, [から]…[まで] de… à….",
      "Fin de phrase : [ね] (n'est-ce pas ?), [よ] (je te l'apprends) ; phrase + [が] = mais.",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Qui a mangé le gâteau ?", answer: "だれがケーキを食べましたか。", wrong: ["だれはケーキを食べましたか。", "だれをケーキが食べましたか。"] },
        { fr: "Moi aussi, je suis étudiant·e.", answer: "私も学生です。", wrong: ["私は学生もです。", "私と学生です。"] },
        { fr: "Je suis allé·e au cinéma avec ma mère.", answer: "母と映画館に行きました。", wrong: ["母や映画館に行きました。", "母の映画館に行きました。"] },
        { fr: "J'ai acheté des pommes, des oranges, etc.", answer: "りんごやみかんを買いました。", wrong: ["りんごもみかんを買いました。", "りんごのみかんを買いました。"] },
        { fr: "C'est le livre de mon ami.", answer: "友達の本です。", wrong: ["本の友達です。", "友達と本です。"] },
        { fr: "Je marche de la maison jusqu'à l'école.", answer: "家から学校まで歩きます。", wrong: ["家まで学校から歩きます。", "学校から家まで歩きます。"] },
        { fr: "J'aime les chats.", answer: "猫が好きです。", wrong: ["猫を好きです。", "猫で好きです。"] },
        { fr: "Mon père et ma mère sont tous les deux médecins.", answer: "父も母も医者です。", wrong: ["父の母も医者です。", "父も母は医者です。"] },
        { fr: "C'est cher, mais c'est bon.", answer: "高いですが、おいしいです。", wrong: ["高いですと、おいしいです。", "高いですや、おいしいです。"] },
        { fr: "Il fait beau, hein ?", answer: "いい天気ですね。", wrong: ["いい天気ですか。", "いい天気をですね。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Moi aussi.", answers: ["私もです。", "わたしもです。"] },
        { fr: "C'est mon livre.", answers: ["私の本です。", "わたしのほんです。"] },
        { fr: "Je vais au Japon avec un ami.", answers: ["友達と日本に行きます。", "ともだちとにほんにいきます。", "友達と日本へ行きます。", "ともだちとにほんへいきます。"] },
        { fr: "Qui est venu ?", answers: ["だれが来ましたか。", "だれがきましたか。"] },
        { fr: "De 9 h à 17 h.", answers: ["九時から五時まで。", "くじからごじまで。", "九時から五時までです。", "くじからごじまでです。"] },
        { fr: "J'aime les chiens.", answers: ["犬が好きです。", "いぬがすきです。"] },
      ],
    },
    morePractice: { href: "/exercices/grammaire?point=n5-wa-desu", label: "Plus de phrases avec は" },
  },
  {
    id: "n5-adjectifs",
    title: "Les adjectifs en profondeur : passé, négatif, liaison, なる",
    minutes: 18,
    summary: "Conjuguer les adjectifs au passé et au négatif, les enchaîner, et dire « devenir ».",
    sections: [
      {
        title: "Les quatre formes",
        formula: "高い → [高くない・高かった・高くなかった]　／　静か → [静かじゃない・静かだった・静かじゃなかった]",
        paragraphs: [
          "Adjectifs en い : on remplace い par [くない] (négatif), [かった] (passé), [くなかった] (passé négatif), puis です pour la politesse : 高[かった]です.",
          "Adjectifs en な : ils se conjuguent comme un nom, avec [じゃありません], [でした], [じゃありませんでした] : 静か[でした].",
        ],
        examples: [
          { ja: "昨日は寒[かった]です。", reading: "きのうはさむ[かった]です。", romaji: "Kinou wa samu[katta] desu.", fr: "Hier, il faisait froid." },
          { ja: "この映画はおもしろ[くない]です。", reading: "このえいがはおもしろ[くない]です。", romaji: "Kono eiga wa omoshiro[kunai] desu.", fr: "Ce film n'est pas intéressant." },
          { ja: "町は静か[でした]。", reading: "まちはしずか[でした]。", romaji: "Machi wa shizuka [deshita].", fr: "La ville était calme." },
        ],
        tip: "Le passé se met **dans l'adjectif** : [高かったです], jamais 高いでした. Et いい devient [よかった] / [よくない].",
      },
      {
        title: "Devant un nom, et pour enchaîner",
        formula: "高い + 山　／　静か[な] + 町　／　高[くて]、…　静か[で]、…",
        paragraphs: [
          "Devant un nom : l'adjectif en い ne change pas (高い山), l'adjectif en な prend [な] (静か[な]町).",
          "Pour enchaîner deux adjectifs (« et ») : い → [くて] (安[くて]おいしい), な → [で] (静か[で]きれい).",
        ],
        examples: [
          { ja: "大き[くて]白い犬です。", reading: "おおき[くて]しろいいぬです。", romaji: "Ooki[kute] shiroi inu desu.", fr: "C'est un grand chien blanc." },
          { ja: "この店は安[くて]おいしいです。", reading: "このみせはやす[くて]おいしいです。", romaji: "Kono mise wa yasu[kute] oishii desu.", fr: "Ce restaurant est bon marché et délicieux." },
          { ja: "きれい[な]部屋ですね。", reading: "きれい[な]へやですね。", romaji: "Kirei [na] heya desu ne.", fr: "Quelle jolie chambre !" },
        ],
        tip: "きれい finit par い mais c'est un adjectif en **な** : きれい[な]部屋, きれい[じゃない].",
      },
      {
        title: "Devenir : なる",
        formula: "い → [くなる]　／　な ou nom → [になる]",
        paragraphs: ["[なる] veut dire « devenir ». Adjectif en い : い → [くなります] (寒くなります, il commence à faire froid). Adjectif en な ou nom : + [になります] (元気になります, 先生になります)."],
        examples: [
          { ja: "暑[くなりました]ね。", reading: "あつ[くなりました]ね。", romaji: "Atsu[ku narimashita] ne.", fr: "Il fait plus chaud, hein." },
          { ja: "医者[になりたい]です。", reading: "いしゃ[になりたい]です。", romaji: "Isha [ni naritai] desu.", fr: "Je veux devenir médecin." },
          { ja: "部屋がきれい[になりました]。", reading: "へやがきれい[になりました]。", romaji: "Heya ga kirei [ni narimashita].", fr: "La chambre est devenue propre." },
        ],
      },
    ],
    vocabulary: [
      { ja: "大きい", reading: "おおきい", fr: "grand" },
      { ja: "小さい", reading: "ちいさい", fr: "petit" },
      { ja: "白い", reading: "しろい", fr: "blanc" },
      { ja: "長い", reading: "ながい", fr: "long" },
      { ja: "静か", reading: "しずか", fr: "calme" },
      { ja: "きれい", reading: "きれい", fr: "joli, propre" },
      { ja: "暑い", reading: "あつい", fr: "chaud (temps)" },
      { ja: "寒い", reading: "さむい", fr: "froid (temps)" },
    ],
    kanji: ["大", "小", "高", "長", "白"],
    keyPoints: [
      "い : [くない / かった / くなかった] + です ; な : [じゃありません / でした].",
      "Devant un nom : 高い山, 静か[な]町 ; enchaîner : [くて] / [で].",
      "Devenir : い → [くなる], な ou nom → [になる].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Hier, il faisait froid.", answer: "昨日は寒かったです。", wrong: ["昨日は寒いでした。", "昨日は寒くないです。"] },
        { fr: "Ce film n'était pas intéressant.", answer: "その映画はおもしろくなかったです。", wrong: ["その映画はおもしろいじゃなかったです。", "その映画はおもしろかったです。"] },
        { fr: "La chambre était propre.", answer: "部屋はきれいでした。", wrong: ["部屋はきれかったです。", "部屋はきれいかったです。"] },
        { fr: "C'est une ville calme.", answer: "静かな町です。", wrong: ["静か町です。", "静かの町です。"] },
        { fr: "C'est un grand chien blanc.", answer: "大きくて白い犬です。", wrong: ["大きいて白い犬です。", "大きいと白い犬です。"] },
        { fr: "Ce n'est pas bien.", answer: "よくないです。", wrong: ["いくないです。", "いいじゃないです。"] },
        { fr: "Il commence à faire froid.", answer: "寒くなりました。", wrong: ["寒いになりました。", "寒くでなりました。"] },
        { fr: "Je veux devenir professeur.", answer: "先生になりたいです。", wrong: ["先生くなりたいです。", "先生がなりたいです。"] },
        { fr: "C'est calme et joli.", answer: "静かできれいです。", wrong: ["静かくてきれいです。", "静かなきれいです。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Il faisait chaud.", answers: ["暑かったです。", "あつかったです。"] },
        { fr: "Ce n'est pas cher.", answers: ["高くないです。", "たかくないです。", "高くありません。", "たかくありません。"] },
        { fr: "C'était calme.", answers: ["静かでした。", "しずかでした。"] },
        { fr: "C'est un long film.", answers: ["長い映画です。", "ながいえいがです。"] },
        { fr: "C'était bien.", answers: ["よかったです。", "良かったです。"] },
        { fr: "Il commence à faire froid.", answers: ["寒くなりました。", "さむくなりました。"] },
      ],
    },
  },
  {
    id: "n5-formes-simples",
    title: "Les formes simples : dictionnaire, ない, た",
    minutes: 18,
    summary: "Les trois groupes de verbes et les formes familières, indispensables pour la suite de la grammaire.",
    sections: [
      {
        title: "Trois groupes de verbes",
        formula: "Groupe 1 : [書く, 飲む, 買う]…　Groupe 2 : [食べる, 見る]　Irréguliers : [する, 来る]",
        paragraphs: [
          "La **forme du dictionnaire** est la forme de base : 食べる, 行く. C'est celle des dictionnaires et des conversations entre amis.",
          "**Groupe 2** : verbes dont le son avant る est en « e » ou en « i », au radical fixe (食べ-る, 見-る). **Groupe 1** : tous les autres (書く, 飲む, 話す…), plus quelques verbes en る comme [帰る], [入る], [走る] et [知る]. **Irréguliers** : [する] et [来る].",
          "Depuis la forme en ます : groupe 1, le son en -i passe en -u (書きます → 書く) ; groupe 2, ます → る (食べます → 食べる).",
        ],
        examples: [
          { ja: "毎朝コーヒーを飲[む]。", reading: "まいあさコーヒーをの[む]。", romaji: "Maiasa koohii o no[mu].", fr: "Je bois un café tous les matins (familier)." },
          { ja: "明日、友達が来[る]。", reading: "あした、ともだちがく[る]。", romaji: "Ashita, tomodachi ga ku[ru].", fr: "Demain, un ami vient (familier)." },
        ],
        tip: "帰る (rentrer) ressemble à un groupe 2 mais c'est un **groupe 1** : 帰ります, 帰らない, 帰って.",
      },
      {
        title: "La forme en ない (négatif)",
        formula: "Groupe 1 : son en u → [son en a + ない]　Groupe 2 : る → [ない]　する → [しない]　来る → [来ない]",
        paragraphs: [
          "Groupe 1 : le dernier son passe en -a, puis ない : 書く → 書[かない], 飲む → 飲[まない]. Les verbes en う donnent [わない] : 買う → 買[わない].",
          "Groupe 2 : る → ない (食べ[ない]). Irréguliers : [しない] et [来ない] (こない).",
        ],
        examples: [
          { ja: "今日は行[かない]。", reading: "きょうはい[かない]。", romaji: "Kyou wa i[kanai].", fr: "Aujourd'hui, je n'y vais pas (familier)." },
          { ja: "肉を食べ[ない]。", reading: "にくをたべ[ない]。", romaji: "Niku o tabe[nai].", fr: "Je ne mange pas de viande (familier)." },
        ],
        tip: "ある devient [ない] tout court, pas あらない : お金がない (je n'ai pas d'argent).",
      },
      {
        title: "La forme en た (passé)",
        formula: "Comme la forme en て, avec [た] : 書いて → [書いた]　読んで → [読んだ]",
        paragraphs: [
          "Bonne nouvelle : la forme en た se fabrique **exactement comme la forme en て**, avec た au lieu de て (et だ au lieu de で) : 読んで → 読[んだ], 書いて → 書[いた], 食べて → 食べ[た].",
          "Passé négatif : ない → [なかった] (行かなかった, je n'y suis pas allé·e).",
        ],
        examples: [
          { ja: "昨日、映画を見[た]。", reading: "きのう、えいがをみ[た]。", romaji: "Kinou, eiga o mi[ta].", fr: "Hier, j'ai vu un film (familier)." },
          { ja: "本を読[んだ]。", reading: "ほんをよ[んだ]。", romaji: "Hon o yo[nda].", fr: "J'ai lu un livre (familier)." },
          { ja: "朝ごはんを食べ[なかった]。", reading: "あさごはんをたべ[なかった]。", romaji: "Asagohan o tabe[nakatta].", fr: "Je n'ai pas pris de petit-déjeuner (familier)." },
        ],
        tip: "行く suit la même exception qu'en て : [行った], jamais 行いた.",
      },
    ],
    vocabulary: [
      { ja: "飲む", reading: "のむ", fr: "boire" },
      { ja: "聞く", reading: "きく", fr: "écouter, demander" },
      { ja: "見る", reading: "みる", fr: "voir, regarder" },
      { ja: "帰る", reading: "かえる", fr: "rentrer" },
      { ja: "来る", reading: "くる", fr: "venir" },
      { ja: "行く", reading: "いく", fr: "aller" },
      { ja: "肉", reading: "にく", fr: "viande" },
    ],
    kanji: ["行", "来", "食", "見", "聞"],
    keyPoints: [
      "Groupe 2 : 食べる, 見る ; groupe 1 : les autres (et 帰る, 入る, 走る, 知る) ; irréguliers : する, 来る.",
      "ない : 書[かない], 買[わない], 食べ[ない], [しない], [来ない].",
      "た : comme la forme en て (読[んだ], 書[いた]) ; passé négatif : [なかった].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Je n'y vais pas (familier).", answer: "行かない。", wrong: ["行きない。", "行くない。"] },
        { fr: "Je ne mange pas (familier).", answer: "食べない。", wrong: ["食べらない。", "食べかない。"] },
        { fr: "Je n'achète pas (familier).", answer: "買わない。", wrong: ["買あない。", "買らない。"] },
        { fr: "Je ne le fais pas (familier).", answer: "しない。", wrong: ["すない。", "さない。"] },
        { fr: "Je n'ai pas d'argent (familier).", answer: "お金がない。", wrong: ["お金があらない。", "お金がいない。"] },
        { fr: "Je ne rentre pas (familier).", answer: "帰らない。", wrong: ["帰ない。", "帰りない。"] },
        { fr: "J'ai lu (familier).", answer: "読んだ。", wrong: ["読みた。", "読った。"] },
        { fr: "J'ai écouté de la musique (familier).", answer: "音楽を聞いた。", wrong: ["音楽を聞きた。", "音楽を聞った。"] },
        { fr: "Il n'est pas venu (familier).", answer: "来なかった。", wrong: ["来ないだった。", "来なくた。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Je mange (familier).", answers: ["食べる。", "たべる。"] },
        { fr: "Je ne bois pas (familier).", answers: ["飲まない。", "のまない。"] },
        { fr: "J'ai vu (familier).", answers: ["見た。", "みた。"] },
        { fr: "Je ne rentre pas (familier).", answers: ["帰らない。", "かえらない。"] },
        { fr: "Je suis allé·e (familier).", answers: ["行った。", "いった。"] },
        { fr: "Je n'ai pas mangé (familier).", answers: ["食べなかった。", "たべなかった。"] },
      ],
    },
    morePractice: { href: "/conjugaison", label: "S'entraîner à conjuguer" },
  },
  {
    id: "n5-avant-apres",
    title: "Avant, après, et plusieurs actions : まえに, てから, たり",
    minutes: 15,
    summary: "Dire ce qu'on fait avant ou après autre chose, et citer quelques activités parmi d'autres.",
    sections: [
      {
        title: "Avant de… : まえに",
        formula: "Verbe au dictionnaire + [まえに]　／　Nom + [の前に]",
        paragraphs: [
          "« Avant de faire » : verbe **à la forme du dictionnaire** + [まえに], même si l'action est passée : 寝る[まえに]本を読みます.",
          "Avec un nom : [の前に] (食事[の前に], avant le repas).",
        ],
        examples: [
          { ja: "寝る[前に]本を読みます。", reading: "ねる[まえに]ほんをよみます。", romaji: "Neru [mae ni] hon o yomimasu.", fr: "Je lis avant de dormir." },
          { ja: "食事[の前に]手を洗います。", reading: "しょくじ[のまえに]てをあらいます。", romaji: "Shokuji [no mae ni] te o araimasu.", fr: "Je me lave les mains avant le repas." },
        ],
        tip: "Jamais de passé devant まえに : 寝た前に est faux, même pour parler d'hier.",
      },
      {
        title: "Après : てから et あとで",
        formula: "Verbe en て + [から]　／　Verbe en た + [あとで]　／　Nom + [のあとで]",
        paragraphs: [
          "[てから] : « après avoir fait…, (ensuite) » ; on insiste sur l'**ordre** des actions : 宿題をして[から]、遊びます.",
          "[たあとで] : « après » ; plus neutre : 学校が終わった[あとで]. Avec un nom : 授業[のあとで].",
        ],
        examples: [
          { ja: "宿題をして[から]、テレビを見ます。", reading: "しゅくだいをして[から]、テレビをみます。", romaji: "Shukudai o shite [kara], terebi o mimasu.", fr: "Je regarde la télé après avoir fait mes devoirs." },
          { ja: "学校が終わった[あとで]、友達と遊びました。", reading: "がっこうがおわった[あとで]、ともだちとあそびました。", romaji: "Gakkou ga owatta [ato de], tomodachi to asobimashita.", fr: "Après l'école, j'ai joué avec des amis." },
          { ja: "授業[のあとで]図書館に行きます。", reading: "じゅぎょう[のあとで]としょかんにいきます。", romaji: "Jugyou [no ato de] toshokan ni ikimasu.", fr: "Après le cours, je vais à la bibliothèque." },
        ],
        tip: "Ne confonds pas てから (après avoir fait) et から après です ou ます (parce que) : 食べてから ≠ 食べますから.",
      },
      {
        title: "Faire ceci, cela… : ～たり～たりする",
        formula: "Verbe en た + [り]、verbe en た + [り] + します",
        paragraphs: [
          "Pour citer **quelques** activités parmi d'autres : forme en た + [り], deux fois, puis します à la fin. 週末は本を読んだり、映画を見たりします.",
          "Le temps se met sur する, à la fin : ～たりしました (passé).",
        ],
        examples: [
          { ja: "日曜日は掃除をし[たり]、買い物をし[たり]します。", reading: "にちようびはそうじをし[たり]、かいものをし[たり]します。", romaji: "Nichiyoubi wa souji o shi[tari], kaimono o shi[tari] shimasu.", fr: "Le dimanche, je fais le ménage, les courses, etc." },
          { ja: "休みの日は寝[たり]、音楽を聞い[たり]しました。", reading: "やすみのひはね[たり]、おんがくをきい[たり]しました。", romaji: "Yasumi no hi wa ne[tari], ongaku o kii[tari] shimashita.", fr: "Pendant mon jour de congé, j'ai dormi, écouté de la musique, etc." },
        ],
        tip: "N'oublie pas します à la fin : 読んだり、見たり tout seul ne fait pas une phrase complète.",
      },
    ],
    vocabulary: [
      { ja: "寝る", reading: "ねる", fr: "dormir, se coucher" },
      { ja: "宿題", reading: "しゅくだい", fr: "devoirs" },
      { ja: "勉強", reading: "べんきょう", fr: "études, travail scolaire" },
      { ja: "掃除", reading: "そうじ", fr: "ménage" },
      { ja: "洗う", reading: "あらう", fr: "laver" },
      { ja: "遊ぶ", reading: "あそぶ", fr: "jouer, s'amuser" },
      { ja: "学校", reading: "がっこう", fr: "école" },
      { ja: "時間", reading: "じかん", fr: "temps, durée" },
    ],
    kanji: ["学", "校", "間"],
    keyPoints: [
      "Avant : verbe au dictionnaire + [まえに] ; nom + [の前に].",
      "Après : verbe en て + [から] ; verbe en た + [あとで] ; nom + [のあとで].",
      "Quelques activités : ～[たり]、～[たり] + します.",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Je lis avant de dormir.", answer: "寝る前に本を読みます。", wrong: ["寝た前に本を読みます。", "寝て前に本を読みます。"] },
        { fr: "Je me lave les mains avant le repas.", answer: "食事の前に手を洗います。", wrong: ["食事のあとで手を洗います。", "食事するの前に手を洗います。"] },
        { fr: "Je regarde la télé après avoir fait mes devoirs.", answer: "宿題をしてから、テレビを見ます。", wrong: ["宿題をしたから、テレビを見ます。", "宿題をする前に、テレビを見ます。"] },
        { fr: "Après l'école, je joue avec des amis.", answer: "学校のあとで、友達と遊びます。", wrong: ["学校のあとで、友達を遊びます。", "学校が前に、友達と遊びます。"] },
        { fr: "Après le repas, j'ai bu un café.", answer: "食事のあとで、コーヒーを飲みました。", wrong: ["食事の前に、コーヒーを飲みました。", "食事してあとで、コーヒーを飲みました。"] },
        { fr: "Le dimanche, je fais le ménage, les courses, etc.", answer: "日曜日は掃除をしたり、買い物をしたりします。", wrong: ["日曜日は掃除をしたり、買い物をしたりです。", "日曜日は掃除をして、買い物をしてりします。"] },
        { fr: "Hier, j'ai lu, regardé la télé, etc.", answer: "昨日は本を読んだり、テレビを見たりしました。", wrong: ["昨日は本を読みたり、テレビを見たりしました。", "昨日は本を読んだり、テレビを見たりします。"] },
        { fr: "Je prends une douche avant de sortir.", answer: "出かける前にシャワーを浴びます。", wrong: ["出かけた前にシャワーを浴びます。", "出かけてから前にシャワーを浴びます。"] },
        { fr: "Je rentre après avoir fait les courses.", answer: "買い物をしてから、帰ります。", wrong: ["買い物をしたから、帰ります。", "買い物をして前に、帰ります。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Je lis avant de dormir.", answers: ["寝る前に本を読みます。", "ねるまえにほんをよみます。"] },
        { fr: "Après avoir mangé, je sors.", answers: ["食べてから、出かけます。", "たべてから、でかけます。"] },
        { fr: "Après l'école, je joue.", answers: ["学校のあとで、遊びます。", "がっこうのあとで、あそびます。", "学校の後で、遊びます。"] },
        { fr: "Je me lave les mains avant le repas.", answers: ["食事の前に手を洗います。", "しょくじのまえにてをあらいます。"] },
        { fr: "Je lis, je regarde des films, etc.", answers: ["本を読んだり、映画を見たりします。", "ほんをよんだり、えいがをみたりします。"] },
        { fr: "Je rentre après avoir fait les courses.", answers: ["買い物をしてから、帰ります。", "かいものをしてから、かえります。"] },
      ],
    },
  },
  {
    id: "n5-envies",
    title: "Envies et talents : たい, ほしい, ～に行く, 上手, わかる",
    minutes: 15,
    summary: "Dire ce qu'on veut faire ou avoir, pourquoi on se déplace, et ce qu'on sait bien faire.",
    sections: [
      {
        title: "Vouloir faire, vouloir avoir",
        formula: "Verbe sans ます + [たいです] (faire)　／　Nom + が + [ほしいです] (avoir)",
        paragraphs: [
          "[たい] dit ce qu'on **veut faire** : 行き[たい]です. Il se conjugue comme un adjectif en い : 行きたくないです, 行きたかったです.",
          "[ほしい] dit ce qu'on **veut avoir** : 車[が]ほしいです. Lui aussi se conjugue comme un adjectif : ほしくないです.",
        ],
        examples: [
          { ja: "新しい車が[ほしいです]。", reading: "あたらしいくるまが[ほしいです]。", romaji: "Atarashii kuruma ga [hoshii desu].", fr: "Je veux une nouvelle voiture." },
          { ja: "今日は何も食べ[たくないです]。", reading: "きょうはなにもたべ[たくないです]。", romaji: "Kyou wa nani mo tabe[takunai desu].", fr: "Aujourd'hui, je ne veux rien manger." },
          { ja: "富士山に登り[たかったです]。", reading: "ふじさんにのぼり[たかったです]。", romaji: "Fujisan ni nobori[takatta desu].", fr: "Je voulais gravir le mont Fuji." },
        ],
        tip: "たい et ほしい parlent de **toi**, ou servent à poser la question (何がほしいですか). Pour quelqu'un d'autre, le japonais utilise d'autres tournures.",
      },
      {
        title: "Aller faire : ～に行く",
        formula: "Verbe sans ます + [に] + 行く / 来る / 帰る",
        paragraphs: [
          "Pour dire **le but** d'un déplacement : verbe sans ます + [に] + 行きます : 映画を見[に]行きます (je vais voir un film).",
          "Avec un nom d'activité, directement : 買い物[に]行きます, 旅行[に]行きます.",
        ],
        examples: [
          { ja: "山へ写真を撮り[に]行きます。", reading: "やまへしゃしんをとり[に]いきます。", romaji: "Yama e shashin o tori [ni] ikimasu.", fr: "Je vais à la montagne pour prendre des photos." },
          { ja: "川へ泳ぎ[に]行きませんか。", reading: "かわへおよぎ[に]いきませんか。", romaji: "Kawa e oyogi [ni] ikimasen ka.", fr: "Et si on allait nager à la rivière ?" },
          { ja: "昼ごはんを食べ[に]帰ります。", reading: "ひるごはんをたべ[に]かえります。", romaji: "Hirugohan o tabe [ni] kaerimasu.", fr: "Je rentre déjeuner." },
        ],
        tip: "On met le verbe **sans ます**, pas au dictionnaire : 見[に]行きます, jamais 見るに行きます.",
      },
      {
        title: "Goûts et talents : が好き, が上手, がわかる",
        formula: "Nom + [が] + 好き・嫌い・上手・下手・わかる",
        paragraphs: [
          "Avec ces mots, l'objet prend [が], pas を : 料理[が]上手です (il cuisine bien), 日本語[が]わかります (je comprends le japonais).",
          "[上手] (doué) et [下手] (pas doué) se disent surtout des **autres** ; pour soi, on reste modeste : まだ下手です.",
        ],
        examples: [
          { ja: "母は料理[が]上手です。", reading: "はははりょうり[が]じょうずです。", romaji: "Haha wa ryouri [ga] jouzu desu.", fr: "Ma mère cuisine très bien." },
          { ja: "少し日本語[が]わかります。", reading: "すこしにほんご[が]わかります。", romaji: "Sukoshi nihongo [ga] wakarimasu.", fr: "Je comprends un peu le japonais." },
          { ja: "私は歌[が]下手です。", reading: "わたしはうた[が]へたです。", romaji: "Watashi wa uta [ga] heta desu.", fr: "Je chante mal." },
        ],
        tip: "日本語をわかります est faux : わかる prend toujours [が].",
      },
    ],
    vocabulary: [
      { ja: "欲しい", reading: "ほしい", fr: "vouloir (avoir)" },
      { ja: "上手", reading: "じょうず", fr: "doué, habile" },
      { ja: "下手", reading: "へた", fr: "maladroit, pas doué" },
      { ja: "料理", reading: "りょうり", fr: "cuisine, plat" },
      { ja: "山", reading: "やま", fr: "montagne" },
      { ja: "川", reading: "かわ", fr: "rivière" },
      { ja: "泳ぐ", reading: "およぐ", fr: "nager" },
      { ja: "旅行", reading: "りょこう", fr: "voyage" },
    ],
    kanji: ["山", "川"],
    keyPoints: [
      "Vouloir faire : verbe sans ます + [たい] ; vouloir avoir : nom + が + [ほしい].",
      "But d'un déplacement : verbe sans ます + [に] + 行く.",
      "好き, 上手, 下手, わかる : l'objet prend [が].",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Je veux un nouveau vélo.", answer: "新しい自転車がほしいです。", wrong: ["新しい自転車にほしいです。", "新しい自転車がほしいたいです。"] },
        { fr: "Je veux aller au Japon.", answer: "日本に行きたいです。", wrong: ["日本に行くたいです。", "日本に行きほしいです。"] },
        { fr: "Je ne veux pas travailler.", answer: "働きたくないです。", wrong: ["働きたいじゃないです。", "働きたいないです。"] },
        { fr: "Je voulais manger des sushis.", answer: "すしを食べたかったです。", wrong: ["すしを食べたいでした。", "すしを食べたくなかったです。"] },
        { fr: "Je vais voir un film.", answer: "映画を見に行きます。", wrong: ["映画を見るに行きます。", "映画を見にで行きます。"] },
        { fr: "Je vais faire les courses.", answer: "買い物に行きます。", wrong: ["買い物を行きます。", "買い物で行きます。"] },
        { fr: "Ma mère cuisine bien.", answer: "母は料理が上手です。", wrong: ["母は料理を上手です。", "母は料理が下手です。"] },
        { fr: "Je comprends le japonais.", answer: "日本語がわかります。", wrong: ["日本語をわかります。", "日本語でわかります。"] },
        { fr: "Qu'est-ce que tu veux (avoir) ?", answer: "何がほしいですか。", wrong: ["何をほしいですか。", "何がほしいますか。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Je veux une voiture.", answers: ["車がほしいです。", "くるまがほしいです。", "車が欲しいです。"] },
        { fr: "Je veux aller au Japon.", answers: ["日本に行きたいです。", "にほんにいきたいです。", "日本へ行きたいです。", "にほんへいきたいです。"] },
        { fr: "Je vais voir un film.", answers: ["映画を見に行きます。", "えいがをみにいきます。"] },
        { fr: "Je comprends un peu.", answers: ["少しわかります。", "すこしわかります。", "少し分かります。"] },
        { fr: "Je ne veux pas manger.", answers: ["食べたくないです。", "たべたくないです。"] },
        { fr: "Tu es doué·e !", answers: ["上手ですね。", "じょうずですね。", "上手です。", "じょうずです。"] },
      ],
    },
    morePractice: { href: "/exercices/grammaire?point=n5-tai", label: "Plus de phrases avec ～たい" },
  },
  {
    id: "n5-compteurs",
    title: "Compter les choses : つ, 人, 本, 枚, 回",
    minutes: 15,
    summary: "Les compteurs : le bon mot selon ce qu'on compte, et où placer la quantité dans la phrase.",
    sections: [
      {
        title: "Un compteur par type d'objet",
        formula: "Nom + を + [nombre + compteur] + verbe",
        paragraphs: [
          "En japonais, on ne dit pas « trois pommes » directement : on ajoute un **compteur** qui dépend de ce qu'on compte. La quantité se place en général **après** le nom et sa particule, juste avant le verbe : りんごを[三つ]買います.",
          "Le compteur passe-partout : [つ] (ひとつ, ふたつ, みっつ, よっつ, いつつ, むっつ, ななつ, やっつ, ここのつ, とお), pour les objets jusqu'à dix.",
        ],
        examples: [
          { ja: "りんごを[三つ]ください。", reading: "りんごを[みっつ]ください。", romaji: "Ringo o [mittsu] kudasai.", fr: "Trois pommes, s'il vous plaît." },
          { ja: "質問が[一つ]あります。", reading: "しつもんが[ひとつ]あります。", romaji: "Shitsumon ga [hitotsu] arimasu.", fr: "J'ai une question." },
        ],
        tip: "Pour demander combien : [いくつ] avec つ ; avec les autres compteurs, 何 + compteur ([何人], [何本], [何枚]).",
      },
      {
        title: "Les personnes : 人",
        formula: "[一人] ひとり　[二人] ふたり　puis nombre + [人] (にん)",
        paragraphs: [
          "Pour les gens, les deux premiers sont irréguliers : [一人] (ひとり) et [二人] (ふたり). Ensuite c'est régulier : 三人 (さんにん), 四人 (よにん), 五人 (ごにん)…",
          "一人で = **seul·e** : 一人で住んでいます (j'habite seul·e).",
        ],
        examples: [
          { ja: "家族は[四人]です。", reading: "かぞくは[よにん]です。", romaji: "Kazoku wa [yonin] desu.", fr: "Nous sommes quatre dans la famille." },
          { ja: "[一人]で旅行しました。", reading: "[ひとり]でりょこうしました。", romaji: "[Hitori] de ryokou shimashita.", fr: "J'ai voyagé seul·e." },
        ],
        tip: "Quatre personnes : [よにん], ni よんにん ni しにん.",
      },
      {
        title: "Objets longs, objets plats, et les fois : 本, 枚, 回",
        formula: "[本] objet long　[枚] objet plat　[回] nombre de fois",
        paragraphs: [
          "[本] (ほん) compte les objets **longs** : stylos, bouteilles, parapluies. Le son change : 一本 (いっぽん), 三本 (さんぼん), 六本 (ろっぽん).",
          "[枚] (まい) compte les objets **plats** : feuilles, timbres, chemises, assiettes. [回] (かい) compte les **fois** : 一回, 二回 ; « deux fois par semaine » : 週に[二回].",
        ],
        examples: [
          { ja: "ペンを[二本]持っています。", reading: "ペンを[にほん]もっています。", romaji: "Pen o [nihon] motte imasu.", fr: "J'ai deux stylos." },
          { ja: "切手を[五枚]買いました。", reading: "きってを[ごまい]かいました。", romaji: "Kitte o [gomai] kaimashita.", fr: "J'ai acheté cinq timbres." },
          { ja: "週に[三回]泳ぎます。", reading: "しゅうに[さんかい]およぎます。", romaji: "Shuu ni [sankai] oyogimasu.", fr: "Je nage trois fois par semaine." },
        ],
      },
    ],
    vocabulary: [
      { ja: "いくつ", reading: "いくつ", fr: "combien (d'objets), quel âge" },
      { ja: "一つ", reading: "ひとつ", fr: "un (objet)" },
      { ja: "二つ", reading: "ふたつ", fr: "deux (objets)" },
      { ja: "一人", reading: "ひとり", fr: "une personne, seul" },
      { ja: "二人", reading: "ふたり", fr: "deux personnes" },
      { ja: "切手", reading: "きって", fr: "timbre" },
      { ja: "家族", reading: "かぞく", fr: "famille" },
      { ja: "質問", reading: "しつもん", fr: "question" },
    ],
    kanji: ["本", "人"],
    keyPoints: [
      "Nom + を + [quantité] + verbe : りんごを[三つ]買います.",
      "Personnes : [一人], [二人], puis 三人, [四人] (よにん)…",
      "[本] long, [枚] plat, [回] fois ; « combien ? » : [いくつ] ou 何 + compteur.",
    ],
    exercise: {
      kind: "lesson-qcm",
      questions: [
        { fr: "Trois pommes, s'il vous plaît.", answer: "りんごを三つください。", wrong: ["りんごを三人ください。", "りんごを三枚ください。"] },
        { fr: "Nous sommes quatre dans la famille.", answer: "家族は四人です。", wrong: ["家族は四つです。", "家族は四本です。"] },
        { fr: "J'ai deux stylos.", answer: "ペンを二本持っています。", wrong: ["ペンを二枚持っています。", "ペンを二人持っています。"] },
        { fr: "J'ai acheté cinq timbres.", answer: "切手を五枚買いました。", wrong: ["切手を五本買いました。", "切手を五回買いました。"] },
        { fr: "J'habite seul·e.", answer: "一人で住んでいます。", wrong: ["一つで住んでいます。", "一人に住んでいます。"] },
        { fr: "Combien de personnes sont venues ?", answer: "何人来ましたか。", wrong: ["いくら来ましたか。", "何本来ましたか。"] },
        { fr: "Je nage deux fois par semaine.", answer: "週に二回泳ぎます。", wrong: ["週に二枚泳ぎます。", "週で二回泳ぎます。"] },
        { fr: "Combien en voulez-vous ?", answer: "いくつほしいですか。", wrong: ["いくらほしいですか。", "何人ほしいですか。"] },
        { fr: "J'ai une question.", answer: "質問が一つあります。", wrong: ["質問が一人あります。", "質問が一本あります。"] },
      ],
    },
    goal: 7,
    writing: {
      goal: 4,
      questions: [
        { fr: "Deux, s'il vous plaît.", answers: ["二つください。", "ふたつください。"] },
        { fr: "Nous sommes trois.", answers: ["三人です。", "さんにんです。"] },
        { fr: "J'habite seul·e.", answers: ["一人で住んでいます。", "ひとりですんでいます。"] },
        { fr: "Une bière, s'il vous plaît.", answers: ["ビールを一本ください。", "ビールをいっぽんください。", "ビールを一つください。", "ビールをひとつください。"] },
        { fr: "Combien de personnes ?", answers: ["何人ですか。", "なんにんですか。"] },
        { fr: "J'ai une question.", answers: ["質問が一つあります。", "しつもんがひとつあります。"] },
      ],
    },
  },
];
