// Mots N5 pour les mini-jeux : lecture en kana, écriture usuelle et sens en
// français. Liste écrite à la main (les listes JLPT du site n'ont ni sens ni
// correspondance écriture -> lecture propres) ; chaque mot est vérifié N5 par
// un test (games.test.ts).

export type GameWord = { kana: string; written: string; fr: string };

export const GAME_WORDS: GameWord[] = [
  // Personnes
  { kana: "わたし", written: "私", fr: "je, moi" },
  { kana: "ともだち", written: "友達", fr: "ami" },
  { kana: "せんせい", written: "先生", fr: "professeur" },
  { kana: "がくせい", written: "学生", fr: "étudiant" },
  { kana: "ひと", written: "人", fr: "personne" },
  { kana: "こども", written: "子供", fr: "enfant" },
  { kana: "ちち", written: "父", fr: "mon père" },
  { kana: "はは", written: "母", fr: "ma mère" },
  { kana: "あに", written: "兄", fr: "mon grand frère" },
  { kana: "あね", written: "姉", fr: "ma grande sœur" },
  { kana: "おとうと", written: "弟", fr: "mon petit frère" },
  { kana: "いもうと", written: "妹", fr: "ma petite sœur" },
  { kana: "かぞく", written: "家族", fr: "famille" },
  { kana: "おとこ", written: "男", fr: "homme" },
  { kana: "おんな", written: "女", fr: "femme" },
  // Animaux et nature
  { kana: "ねこ", written: "猫", fr: "chat" },
  { kana: "いぬ", written: "犬", fr: "chien" },
  { kana: "とり", written: "鳥", fr: "oiseau" },
  { kana: "さかな", written: "魚", fr: "poisson" },
  { kana: "やま", written: "山", fr: "montagne" },
  { kana: "かわ", written: "川", fr: "rivière" },
  { kana: "うみ", written: "海", fr: "mer" },
  { kana: "そら", written: "空", fr: "ciel" },
  { kana: "あめ", written: "雨", fr: "pluie" },
  { kana: "ゆき", written: "雪", fr: "neige" },
  { kana: "はな", written: "花", fr: "fleur" },
  { kana: "き", written: "木", fr: "arbre" },
  { kana: "みず", written: "水", fr: "eau" },
  // Nourriture et boissons
  { kana: "ごはん", written: "ご飯", fr: "riz cuit, repas" },
  { kana: "パン", written: "パン", fr: "pain" },
  { kana: "たまご", written: "卵", fr: "œuf" },
  { kana: "にく", written: "肉", fr: "viande" },
  { kana: "やさい", written: "野菜", fr: "légume" },
  { kana: "くだもの", written: "果物", fr: "fruit" },
  { kana: "おちゃ", written: "お茶", fr: "thé" },
  { kana: "コーヒー", written: "コーヒー", fr: "café" },
  { kana: "ぎゅうにゅう", written: "牛乳", fr: "lait" },
  { kana: "おさけ", written: "お酒", fr: "alcool, saké" },
  { kana: "あさごはん", written: "朝ご飯", fr: "petit-déjeuner" },
  { kana: "ばんごはん", written: "晩ご飯", fr: "dîner" },
  // Lieux
  { kana: "いえ", written: "家", fr: "maison" },
  { kana: "へや", written: "部屋", fr: "chambre, pièce" },
  { kana: "がっこう", written: "学校", fr: "école" },
  { kana: "えき", written: "駅", fr: "gare" },
  { kana: "みせ", written: "店", fr: "magasin" },
  { kana: "こうえん", written: "公園", fr: "parc" },
  { kana: "としょかん", written: "図書館", fr: "bibliothèque" },
  { kana: "びょういん", written: "病院", fr: "hôpital" },
  { kana: "ぎんこう", written: "銀行", fr: "banque" },
  { kana: "まち", written: "町", fr: "ville" },
  { kana: "くに", written: "国", fr: "pays" },
  { kana: "みち", written: "道", fr: "route, chemin" },
  { kana: "レストラン", written: "レストラン", fr: "restaurant" },
  { kana: "トイレ", written: "トイレ", fr: "toilettes" },
  // Objets
  { kana: "ほん", written: "本", fr: "livre" },
  { kana: "かさ", written: "傘", fr: "parapluie" },
  { kana: "かばん", written: "鞄", fr: "sac" },
  { kana: "くつ", written: "靴", fr: "chaussures" },
  { kana: "とけい", written: "時計", fr: "montre, horloge" },
  { kana: "つくえ", written: "机", fr: "bureau (meuble)" },
  { kana: "いす", written: "椅子", fr: "chaise" },
  { kana: "まど", written: "窓", fr: "fenêtre" },
  { kana: "ドア", written: "ドア", fr: "porte" },
  { kana: "でんわ", written: "電話", fr: "téléphone" },
  { kana: "しんぶん", written: "新聞", fr: "journal" },
  { kana: "てがみ", written: "手紙", fr: "lettre" },
  { kana: "しゃしん", written: "写真", fr: "photo" },
  { kana: "えいが", written: "映画", fr: "film" },
  { kana: "おかね", written: "お金", fr: "argent" },
  { kana: "くるま", written: "車", fr: "voiture" },
  { kana: "でんしゃ", written: "電車", fr: "train" },
  { kana: "バス", written: "バス", fr: "bus" },
  { kana: "テレビ", written: "テレビ", fr: "télévision" },
  { kana: "ふく", written: "服", fr: "vêtements" },
  // Corps
  { kana: "め", written: "目", fr: "œil" },
  { kana: "みみ", written: "耳", fr: "oreille" },
  { kana: "くち", written: "口", fr: "bouche" },
  { kana: "て", written: "手", fr: "main" },
  { kana: "あし", written: "足", fr: "pied, jambe" },
  { kana: "あたま", written: "頭", fr: "tête" },
  // Temps
  { kana: "あさ", written: "朝", fr: "matin" },
  { kana: "ひる", written: "昼", fr: "midi, journée" },
  { kana: "よる", written: "夜", fr: "nuit, soir" },
  { kana: "きょう", written: "今日", fr: "aujourd'hui" },
  { kana: "あした", written: "明日", fr: "demain" },
  { kana: "きのう", written: "昨日", fr: "hier" },
  { kana: "いま", written: "今", fr: "maintenant" },
  { kana: "なつ", written: "夏", fr: "été" },
  { kana: "ふゆ", written: "冬", fr: "hiver" },
  { kana: "はる", written: "春", fr: "printemps" },
  { kana: "あき", written: "秋", fr: "automne" },
  { kana: "やすみ", written: "休み", fr: "vacances, repos" },
  // Verbes (forme du dictionnaire)
  { kana: "たべる", written: "食べる", fr: "manger" },
  { kana: "のむ", written: "飲む", fr: "boire" },
  { kana: "いく", written: "行く", fr: "aller" },
  { kana: "くる", written: "来る", fr: "venir" },
  { kana: "かえる", written: "帰る", fr: "rentrer" },
  { kana: "みる", written: "見る", fr: "regarder" },
  { kana: "きく", written: "聞く", fr: "écouter" },
  { kana: "よむ", written: "読む", fr: "lire" },
  { kana: "かく", written: "書く", fr: "écrire" },
  { kana: "はなす", written: "話す", fr: "parler" },
  { kana: "かう", written: "買う", fr: "acheter" },
  { kana: "ねる", written: "寝る", fr: "dormir" },
  { kana: "おきる", written: "起きる", fr: "se lever" },
  { kana: "あるく", written: "歩く", fr: "marcher" },
  { kana: "まつ", written: "待つ", fr: "attendre" },
  { kana: "あう", written: "会う", fr: "rencontrer" },
  // Adjectifs
  { kana: "おおきい", written: "大きい", fr: "grand" },
  { kana: "ちいさい", written: "小さい", fr: "petit" },
  { kana: "たかい", written: "高い", fr: "cher, haut" },
  { kana: "やすい", written: "安い", fr: "bon marché" },
  { kana: "あたらしい", written: "新しい", fr: "nouveau" },
  { kana: "ふるい", written: "古い", fr: "vieux (objet)" },
  { kana: "あつい", written: "暑い", fr: "chaud (temps)" },
  { kana: "さむい", written: "寒い", fr: "froid (temps)" },
  { kana: "おいしい", written: "美味しい", fr: "délicieux" },
  { kana: "たのしい", written: "楽しい", fr: "amusant" },
  { kana: "しずか", written: "静か", fr: "calme" },
  { kana: "げんき", written: "元気", fr: "en forme" },
];

// Mot écrit uniquement en hiragana (grille de mots croisés : une case = un kana).
export const HIRAGANA_ONLY = /^[ぁ-ゖ]+$/;
