// Mots N5 pour les mini-jeux : lecture en kana, écriture usuelle et sens en
// français. Liste écrite à la main (les listes JLPT du site n'ont ni sens ni
// correspondance écriture -> lecture propres) ; chaque mot est vérifié N5 par
// un test (games.test.ts).

export type GameWord = { kana: string; written: string; fr: string };

export const GAME_WORDS: GameWord[] = [
  // Personnes
  { kana: "わたし", written: "私", fr: "je, moi" },
  { kana: "ともだち", written: "友達", fr: "ami" },
  { kana: "せんせい", written: "先生", fr: "professeur" },
  { kana: "がくせい", written: "学生", fr: "étudiant" },
  { kana: "ひと", written: "人", fr: "personne" },
  { kana: "こども", written: "子供", fr: "enfant" },
  { kana: "ちち", written: "父", fr: "mon père" },
  { kana: "はは", written: "母", fr: "ma mère" },
  { kana: "あに", written: "兄", fr: "mon grand frère" },
  { kana: "あね", written: "姉", fr: "ma grande sœur" },
  { kana: "おとうと", written: "弟", fr: "mon petit frère" },
  { kana: "いもうと", written: "妹", fr: "ma petite sœur" },
  { kana: "かぞく", written: "家族", fr: "famille" },
  { kana: "おとこ", written: "男", fr: "homme" },
  { kana: "おんな", written: "女", fr: "femme" },
  // Animaux et nature
  { kana: "ねこ", written: "猫", fr: "chat" },
  { kana: "いぬ", written: "犬", fr: "chien" },
  { kana: "とり", written: "鳥", fr: "oiseau" },
  { kana: "さかな", written: "魚", fr: "poisson" },
  { kana: "やま", written: "山", fr: "montagne" },
  { kana: "かわ", written: "川", fr: "rivière" },
  { kana: "うみ", written: "海", fr: "mer" },
  { kana: "そら", written: "空", fr: "ciel" },
  { kana: "あめ", written: "雨", fr: "pluie" },
  { kana: "ゆき", written: "雪", fr: "neige" },
  { kana: "はな", written: "花", fr: "fleur" },
  { kana: "き", written: "木", fr: "arbre" },
  { kana: "みず", written: "水", fr: "eau" },
  // Nourriture et boissons
  { kana: "ごはん", written: "ご飯", fr: "riz cuit, repas" },
  { kana: "パン", written: "パン", fr: "pain" },
  { kana: "たまご", written: "卵", fr: "œuf" },
  { kana: "にく", written: "肉", fr: "viande" },
  { kana: "やさい", written: "野菜", fr: "légume" },
  { kana: "くだもの", written: "果物", fr: "fruit" },
  { kana: "おちゃ", written: "お茶", fr: "thé" },
  { kana: "コーヒー", written: "コーヒー", fr: "café" },
  { kana: "ぎゅうにゅう", written: "牛乳", fr: "lait" },
  { kana: "おさけ", written: "お酒", fr: "alcool, saké" },
  { kana: "あさごはん", written: "朝ご飯", fr: "petit-déjeuner" },
  { kana: "ばんごはん", written: "晩ご飯", fr: "dîner" },
  // Lieux
  { kana: "いえ", written: "家", fr: "maison" },
  { kana: "へや", written: "部屋", fr: "chambre, pièce" },
  { kana: "がっこう", written: "学校", fr: "école" },
  { kana: "えき", written: "駅", fr: "gare" },
  { kana: "みせ", written: "店", fr: "magasin" },
  { kana: "こうえん", written: "公園", fr: "parc" },
  { kana: "としょかん", written: "図書館", fr: "bibliothèque" },
  { kana: "びょういん", written: "病院", fr: "hôpital" },
  { kana: "ぎんこう", written: "銀行", fr: "banque" },
  { kana: "まち", written: "町", fr: "ville" },
  { kana: "くに", written: "国", fr: "pays" },
  { kana: "みち", written: "道", fr: "route, chemin" },
  { kana: "レストラン", written: "レストラン", fr: "restaurant" },
  { kana: "トイレ", written: "トイレ", fr: "toilettes" },
  // Objets
  { kana: "ほん", written: "本", fr: "livre" },
  { kana: "かさ", written: "傘", fr: "parapluie" },
  { kana: "かばん", written: "鞄", fr: "sac" },
  { kana: "くつ", written: "靴", fr: "chaussures" },
  { kana: "とけい", written: "時計", fr: "montre, horloge" },
  { kana: "つくえ", written: "机", fr: "bureau (meuble)" },
  { kana: "いす", written: "椅子", fr: "chaise" },
  { kana: "まど", written: "窓", fr: "fenêtre" },
  { kana: "ドア", written: "ドア", fr: "porte" },
  { kana: "でんわ", written: "電話", fr: "téléphone" },
  { kana: "しんぶん", written: "新聞", fr: "journal" },
  { kana: "てがみ", written: "手紙", fr: "lettre" },
  { kana: "しゃしん", written: "写真", fr: "photo" },
  { kana: "えいが", written: "映画", fr: "film" },
  { kana: "おかね", written: "お金", fr: "argent" },
  { kana: "くるま", written: "車", fr: "voiture" },
  { kana: "でんしゃ", written: "電車", fr: "train" },
  { kana: "バス", written: "バス", fr: "bus" },
  { kana: "テレビ", written: "テレビ", fr: "télévision" },
  { kana: "ふく", written: "服", fr: "vêtements" },
  // Corps
  { kana: "め", written: "目", fr: "œil" },
  { kana: "みみ", written: "耳", fr: "oreille" },
  { kana: "くち", written: "口", fr: "bouche" },
  { kana: "て", written: "手", fr: "main" },
  { kana: "あし", written: "足", fr: "pied, jambe" },
  { kana: "あたま", written: "頭", fr: "tête" },
  // Temps
  { kana: "あさ", written: "朝", fr: "matin" },
  { kana: "ひる", written: "昼", fr: "midi, journée" },
  { kana: "よる", written: "夜", fr: "nuit, soir" },
  { kana: "きょう", written: "今日", fr: "aujourd'hui" },
  { kana: "あした", written: "明日", fr: "demain" },
  { kana: "きのう", written: "昨日", fr: "hier" },
  { kana: "いま", written: "今", fr: "maintenant" },
  { kana: "なつ", written: "夏", fr: "été" },
  { kana: "ふゆ", written: "冬", fr: "hiver" },
  { kana: "はる", written: "春", fr: "printemps" },
  { kana: "あき", written: "秋", fr: "automne" },
  { kana: "やすみ", written: "休み", fr: "vacances, repos" },
  // Verbes (forme du dictionnaire)
  { kana: "たべる", written: "食べる", fr: "manger" },
  { kana: "のむ", written: "飲む", fr: "boire" },
  { kana: "いく", written: "行く", fr: "aller" },
  { kana: "くる", written: "来る", fr: "venir" },
  { kana: "かえる", written: "帰る", fr: "rentrer" },
  { kana: "みる", written: "見る", fr: "regarder" },
  { kana: "きく", written: "聞く", fr: "écouter" },
  { kana: "よむ", written: "読む", fr: "lire" },
  { kana: "かく", written: "書く", fr: "écrire" },
  { kana: "はなす", written: "話す", fr: "parler" },
  { kana: "かう", written: "買う", fr: "acheter" },
  { kana: "ねる", written: "寝る", fr: "dormir" },
  { kana: "おきる", written: "起きる", fr: "se lever" },
  { kana: "あるく", written: "歩く", fr: "marcher" },
  { kana: "まつ", written: "待つ", fr: "attendre" },
  { kana: "あう", written: "会う", fr: "rencontrer" },
  // Adjectifs
  { kana: "おおきい", written: "大きい", fr: "grand" },
  { kana: "ちいさい", written: "小さい", fr: "petit" },
  { kana: "たかい", written: "高い", fr: "cher, haut" },
  { kana: "やすい", written: "安い", fr: "bon marché" },
  { kana: "あたらしい", written: "新しい", fr: "nouveau" },
  { kana: "ふるい", written: "古い", fr: "vieux (objet)" },
  { kana: "あつい", written: "暑い", fr: "chaud (temps)" },
  { kana: "さむい", written: "寒い", fr: "froid (temps)" },
  { kana: "おいしい", written: "美味しい", fr: "délicieux" },
  { kana: "たのしい", written: "楽しい", fr: "amusant" },
  { kana: "しずか", written: "静か", fr: "calme" },
  { kana: "げんき", written: "元気", fr: "en forme" },
];

// Mots N4 (Memory et Contre la montre, choix « Mots N4 ») : même principe,
// chaque mot vérifié N4 par games.test.ts.
export const GAME_WORDS_N4: GameWord[] = [
  { kana: "いけん", written: "意見", fr: "avis" },
  { kana: "うんてん", written: "運転", fr: "conduite" },
  { kana: "かいじょう", written: "会場", fr: "salle (d'événement)" },
  { kana: "かいがん", written: "海岸", fr: "côte, bord de mer" },
  { kana: "かえり", written: "帰り", fr: "retour" },
  { kana: "かがく", written: "科学", fr: "science" },
  { kana: "かがみ", written: "鏡", fr: "miroir" },
  { kana: "かじ", written: "火事", fr: "incendie" },
  { kana: "かみ", written: "髪", fr: "cheveux" },
  { kana: "かれ", written: "彼", fr: "il, lui" },
  { kana: "かのじょ", written: "彼女", fr: "elle, petite amie" },
  { kana: "きかい", written: "機会", fr: "occasion" },
  { kana: "きけん", written: "危険", fr: "danger" },
  { kana: "きせつ", written: "季節", fr: "saison" },
  { kana: "きそく", written: "規則", fr: "règle" },
  { kana: "きぶん", written: "気分", fr: "humeur" },
  { kana: "きょうかい", written: "教会", fr: "église" },
  { kana: "きょうそう", written: "競争", fr: "compétition" },
  { kana: "きょうみ", written: "興味", fr: "intérêt" },
  { kana: "きんじょ", written: "近所", fr: "voisinage" },
  { kana: "くうき", written: "空気", fr: "air" },
  { kana: "くうこう", written: "空港", fr: "aéroport" },
  { kana: "くさ", written: "草", fr: "herbe" },
  { kana: "くび", written: "首", fr: "cou" },
  { kana: "くも", written: "雲", fr: "nuage" },
  { kana: "けいかく", written: "計画", fr: "projet, plan" },
  { kana: "けいざい", written: "経済", fr: "économie" },
  { kana: "けいさつ", written: "警察", fr: "police" },
  { kana: "けしき", written: "景色", fr: "paysage" },
  { kana: "げんいん", written: "原因", fr: "cause" },
  { kana: "けんきゅう", written: "研究", fr: "recherche" },
  { kana: "こうがい", written: "郊外", fr: "banlieue" },
  { kana: "こうつう", written: "交通", fr: "circulation" },
  { kana: "こうこう", written: "高校", fr: "lycée" },
  { kana: "こくさい", written: "国際", fr: "international" },
  { kana: "こころ", written: "心", fr: "cœur" },
  { kana: "こしょう", written: "故障", fr: "panne" },
  { kana: "こめ", written: "米", fr: "riz (cru)" },
  { kana: "さか", written: "坂", fr: "pente" },
  { kana: "しあい", written: "試合", fr: "match" },
  { kana: "じしん", written: "地震", fr: "tremblement de terre" },
  { kana: "じだい", written: "時代", fr: "époque" },
  { kana: "しなもの", written: "品物", fr: "article, marchandise" },
  { kana: "しま", written: "島", fr: "île" },
  { kana: "しゃかい", written: "社会", fr: "société" },
  { kana: "しゃちょう", written: "社長", fr: "PDG" },
  { kana: "じゆう", written: "自由", fr: "liberté" },
  { kana: "しゅうかん", written: "習慣", fr: "habitude" },
  { kana: "じゅうしょ", written: "住所", fr: "adresse" },
  { kana: "じゅうどう", written: "柔道", fr: "judo" },
  { kana: "しゅみ", written: "趣味", fr: "passe-temps" },
  { kana: "じゅんび", written: "準備", fr: "préparation" },
  { kana: "しょうかい", written: "紹介", fr: "présentation" },
  { kana: "しょうせつ", written: "小説", fr: "roman" },
  { kana: "しょうらい", written: "将来", fr: "avenir" },
  { kana: "じょせい", written: "女性", fr: "femme" },
  { kana: "じんこう", written: "人口", fr: "population" },
  { kana: "じんじゃ", written: "神社", fr: "sanctuaire shinto" },
  { kana: "すいえい", written: "水泳", fr: "natation" },
  { kana: "すうがく", written: "数学", fr: "mathématiques" },
  { kana: "すな", written: "砂", fr: "sable" },
  { kana: "せいじ", written: "政治", fr: "politique" },
  { kana: "せいかつ", written: "生活", fr: "vie quotidienne" },
  { kana: "せなか", written: "背中", fr: "dos" },
  { kana: "せんそう", written: "戦争", fr: "guerre" },
  { kana: "そふ", written: "祖父", fr: "grand-père" },
  { kana: "そぼ", written: "祖母", fr: "grand-mère" },
  { kana: "たいふう", written: "台風", fr: "typhon" },
  { kana: "たたみ", written: "畳", fr: "tatami" },
  { kana: "たな", written: "棚", fr: "étagère" },
  { kana: "ちり", written: "地理", fr: "géographie" },
  { kana: "ちゅうい", written: "注意", fr: "attention" },
  { kana: "つごう", written: "都合", fr: "disponibilité" },
  { kana: "つま", written: "妻", fr: "épouse" },
  { kana: "てぶくろ", written: "手袋", fr: "gants" },
  { kana: "てら", written: "寺", fr: "temple" },
  { kana: "どうぐ", written: "道具", fr: "outil" },
  { kana: "どうぶつえん", written: "動物園", fr: "zoo" },
  { kana: "とっきゅう", written: "特急", fr: "train express" },
  { kana: "どろぼう", written: "泥棒", fr: "voleur" },
  { kana: "にんぎょう", written: "人形", fr: "poupée" },
  { kana: "ねつ", written: "熱", fr: "fièvre" },
  { kana: "のど", written: "喉", fr: "gorge" },
  { kana: "のりもの", written: "乗り物", fr: "véhicule" },
  { kana: "はいしゃ", written: "歯医者", fr: "dentiste" },
  { kana: "ばしょ", written: "場所", fr: "endroit" },
  { kana: "はやし", written: "林", fr: "bois" },
  { kana: "ばんぐみ", written: "番組", fr: "émission" },
  { kana: "ひかり", written: "光", fr: "lumière" },
  { kana: "びじゅつかん", written: "美術館", fr: "musée d'art" },
  { kana: "ひきだし", written: "引き出し", fr: "tiroir" },
  { kana: "ひるま", written: "昼間", fr: "journée" },
  { kana: "ふとん", written: "布団", fr: "futon" },
  { kana: "ふね", written: "船", fr: "bateau" },
  { kana: "ぶんか", written: "文化", fr: "culture" },
  { kana: "ぶんがく", written: "文学", fr: "littérature" },
  { kana: "ほうりつ", written: "法律", fr: "loi" },
  { kana: "ほし", written: "星", fr: "étoile" },
  { kana: "ほんやく", written: "翻訳", fr: "traduction" },
  { kana: "まんが", written: "漫画", fr: "manga" },
  { kana: "みなと", written: "港", fr: "port" },
  { kana: "むかし", written: "昔", fr: "autrefois" },
  { kana: "むすこ", written: "息子", fr: "fils" },
  { kana: "むすめ", written: "娘", fr: "fille" },
  { kana: "もり", written: "森", fr: "forêt" },
  { kana: "やくそく", written: "約束", fr: "promesse" },
  { kana: "ゆめ", written: "夢", fr: "rêve" },
  { kana: "よてい", written: "予定", fr: "programme" },
  { kana: "よやく", written: "予約", fr: "réservation" },
  { kana: "りゆう", written: "理由", fr: "raison" },
  { kana: "りよう", written: "利用", fr: "utilisation" },
  { kana: "りょかん", written: "旅館", fr: "auberge japonaise" },
  { kana: "れきし", written: "歴史", fr: "histoire" },
  { kana: "れんらく", written: "連絡", fr: "contact" },
  { kana: "あつめる", written: "集める", fr: "rassembler" },
  { kana: "あやまる", written: "謝る", fr: "s'excuser" },
  { kana: "いそぐ", written: "急ぐ", fr: "se dépêcher" },
  { kana: "いのる", written: "祈る", fr: "prier" },
  { kana: "うえる", written: "植える", fr: "planter" },
  { kana: "うごく", written: "動く", fr: "bouger" },
  { kana: "うつす", written: "写す", fr: "copier" },
  { kana: "えらぶ", written: "選ぶ", fr: "choisir" },
  { kana: "おくる", written: "送る", fr: "envoyer" },
  { kana: "おこす", written: "起こす", fr: "réveiller" },
  { kana: "おこる", written: "怒る", fr: "se fâcher" },
  { kana: "おちる", written: "落ちる", fr: "tomber" },
  { kana: "おどる", written: "踊る", fr: "danser" },
  { kana: "おどろく", written: "驚く", fr: "être surpris" },
  { kana: "おもいだす", written: "思い出す", fr: "se souvenir" },
  { kana: "きめる", written: "決める", fr: "décider" },
  { kana: "くらべる", written: "比べる", fr: "comparer" },
  { kana: "さがす", written: "探す", fr: "chercher" },
  { kana: "さわぐ", written: "騒ぐ", fr: "faire du bruit" },
  { kana: "しらべる", written: "調べる", fr: "vérifier" },
  { kana: "すてる", written: "捨てる", fr: "jeter" },
  { kana: "そだてる", written: "育てる", fr: "élever" },
  { kana: "たりる", written: "足りる", fr: "suffire" },
  { kana: "とどける", written: "届ける", fr: "livrer" },
  { kana: "とまる", written: "泊まる", fr: "loger" },
  { kana: "なおす", written: "直す", fr: "réparer" },
  { kana: "なれる", written: "慣れる", fr: "s'habituer" },
  { kana: "にげる", written: "逃げる", fr: "s'enfuir" },
  { kana: "はこぶ", written: "運ぶ", fr: "transporter" },
  { kana: "はらう", written: "払う", fr: "payer" },
  { kana: "ひろう", written: "拾う", fr: "ramasser" },
  { kana: "ふえる", written: "増える", fr: "augmenter" },
  { kana: "ほめる", written: "褒める", fr: "féliciter" },
  { kana: "もどる", written: "戻る", fr: "revenir" },
  { kana: "やく", written: "焼く", fr: "griller" },
  { kana: "よろこぶ", written: "喜ぶ", fr: "se réjouir" },
  { kana: "わらう", written: "笑う", fr: "rire" },
  { kana: "われる", written: "割れる", fr: "se casser" },
  { kana: "あさい", written: "浅い", fr: "peu profond" },
  { kana: "うつくしい", written: "美しい", fr: "beau" },
  { kana: "うれしい", written: "嬉しい", fr: "content" },
  { kana: "かたい", written: "固い", fr: "dur" },
  { kana: "かなしい", written: "悲しい", fr: "triste" },
  { kana: "きびしい", written: "厳しい", fr: "sévère" },
  { kana: "こまかい", written: "細かい", fr: "minutieux" },
  { kana: "こわい", written: "怖い", fr: "effrayant" },
  { kana: "さびしい", written: "寂しい", fr: "se sentir seul" },
  { kana: "めずらしい", written: "珍しい", fr: "rare" },
  { kana: "やさしい", written: "優しい", fr: "gentil" },
  { kana: "やわらかい", written: "柔らかい", fr: "mou" },
  { kana: "ふかい", written: "深い", fr: "profond" },
  { kana: "ねむい", written: "眠い", fr: "avoir sommeil" },
  { kana: "にがい", written: "苦い", fr: "amer" },
  { kana: "ていねい", written: "丁寧", fr: "poli" },
  { kana: "とくべつ", written: "特別", fr: "spécial" },
  { kana: "ふくざつ", written: "複雑", fr: "compliqué" },
  { kana: "へん", written: "変", fr: "bizarre" },
  { kana: "あんしん", written: "安心", fr: "soulagement" },
  { kana: "ざんねん", written: "残念", fr: "dommage" },
];

// Mot écrit uniquement en hiragana (grille de mots croisés : une case = un kana).
export const HIRAGANA_ONLY = /^[ぁ-ゖ]+$/;
